/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// AllDom administration
type AllDomAllDom struct {

	// Name of the allDom
	Name string `json:"name,omitempty"`

	// Offer of the allDom
	Offer string `json:"offer,omitempty"`

	// Type of the allDom
	Type_ string `json:"type,omitempty"`
}
