/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// AllDomDomain Domain name of a allDom
type AllDomDomain struct {

	// Domain Domain name
	Domain string `json:"domain,omitempty"`
}
