/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Details about a Refund
type BillingRefund struct {

	Date time.Time `json:"date,omitempty"`

	OrderId int64 `json:"orderId,omitempty"`

	OriginalBillId string `json:"originalBillId,omitempty"`

	Password string `json:"password,omitempty"`

	PdfUrl string `json:"pdfUrl,omitempty"`

	PriceWithTax OrderPrice `json:"priceWithTax,omitempty"`

	PriceWithoutTax OrderPrice `json:"priceWithoutTax,omitempty"`

	RefundId string `json:"refundId,omitempty"`

	Tax OrderPrice `json:"tax,omitempty"`

	Url string `json:"url,omitempty"`
}
