/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Details about a fidelity account
type BillingFidelityMovement struct {

	Amount int64 `json:"amount,omitempty"`

	Balance int64 `json:"balance,omitempty"`

	Date time.Time `json:"date,omitempty"`

	Description string `json:"description,omitempty"`

	MovementId int64 `json:"movementId,omitempty"`

	Operation string `json:"operation,omitempty"`

	Order int64 `json:"order,omitempty"`

	PreviousBalance int64 `json:"previousBalance,omitempty"`
}
