/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// BillingRefundDetail Information about a Bill entry
type BillingRefundDetail struct {
	Description string `json:"description,omitempty"`

	Domain string `json:"domain,omitempty"`

	Quantity string `json:"quantity,omitempty"`

	Reference string `json:"reference,omitempty"`

	RefundDetailID string `json:"refundDetailId,omitempty"`

	RefundID string `json:"refundId,omitempty"`

	TotalPrice *OrderPrice `json:"totalPrice,omitempty"`

	UnitPrice *OrderPrice `json:"unitPrice,omitempty"`
}
