/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Paypal account info
type BillingPaypal struct {

	AgreementId string `json:"agreementId,omitempty"`

	CreationDate time.Time `json:"creationDate,omitempty"`

	DefaultPaymentMean bool `json:"defaultPaymentMean,omitempty"`

	// Custom description of this account
	Description string `json:"description,omitempty"`

	Email string `json:"email,omitempty"`

	Id int64 `json:"id,omitempty"`

	State string `json:"state,omitempty"`
}
