/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CDNWebstorageAccount Static CDN
type CDNWebstorageAccount struct {
	Domain string `json:"domain,omitempty"`

	Server string `json:"server,omitempty"`

	// StorageLimit value in Bytes
	StorageLimit int64 `json:"storageLimit,omitempty"`

	// StorageUsage value in Bytes
	StorageUsage int64 `json:"storageUsage,omitempty"`
}
