/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Zone on CDN
type CdnWebsiteZone struct {

	Status string `json:"status,omitempty"`

	Zone string `json:"zone,omitempty"`
}
