/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Backend on zone
type CdnWebsiteBackend struct {

	Ipv4 string `json:"ipv4,omitempty"`

	Status string `json:"status,omitempty"`
}
