/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CDNanycastCacheRule CacheRules for a domain
type CDNanycastCacheRule struct {

	// CacheRuleID Id for this cache rule
	CacheRuleID int64 `json:"cacheRuleId,omitempty"`

	CacheType string `json:"cacheType,omitempty"`

	Domain string `json:"domain,omitempty"`

	FileMatch string `json:"fileMatch,omitempty"`

	FileType string `json:"fileType,omitempty"`

	Status string `json:"status,omitempty"`

	TTL int64 `json:"ttl,omitempty"`
}
