/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// InstanceVnc
type CloudInstanceInstanceVnc struct {

	// VNC type
	Type_ string `json:"type,omitempty"`

	// VNC url
	Url string `json:"url,omitempty"`
}
