/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Details about flavor pricing
type CloudFlavorPrice struct {

	// Flavor id
	FlavorId string `json:"flavorId,omitempty"`

	// Flavor name
	FlavorName string `json:"flavorName,omitempty"`

	MonthlyPrice OrderPrice `json:"monthlyPrice,omitempty"`

	Price OrderPrice `json:"price,omitempty"`

	// Flavor region
	Region string `json:"region,omitempty"`
}
