/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// CloudAuthenticationOpenstackToken OpenstackToken
type CloudAuthenticationOpenstackToken struct {
	Catalog []*CloudAuthenticationCatalog `json:"catalog,omitempty"`

	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	IssuedAt *time.Time `json:"issued_at,omitempty"`

	Methods []string `json:"methods,omitempty"`

	Project *CloudAuthenticationTokenProject `json:"project,omitempty"`

	Roles []*CloudAuthenticationRole `json:"roles,omitempty"`

	User *CloudAuthenticationUserToken `json:"user,omitempty"`
}
