/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudArchiveStoragePrice Details about archive storage pricing
type CloudArchiveStoragePrice struct {
	MonthlyPrice *OrderPrice `json:"monthlyPrice,omitempty"`

	// Region Archive region
	Region string `json:"region,omitempty"`
}
