/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// NetworkBulkParams
type CloudInstanceNetworkBulkParams struct {

	// Private or public network Id
	NetworkId string `json:"networkId,omitempty"`
}
