/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Snapshot
type CloudVolumeSnapshot struct {

	// Snapshot creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Snapshot description
	Description string `json:"description,omitempty"`

	// Snapshot id
	Id string `json:"id,omitempty"`

	// Snapshot name
	Name string `json:"name,omitempty"`

	// Snapshot region
	Region string `json:"region,omitempty"`

	// Snapshot size
	Size int64 `json:"size,omitempty"`

	// Snapshot status
	Status string `json:"status,omitempty"`

	// Volume source id
	VolumeId string `json:"volumeId,omitempty"`
}
