/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudNetworkRegion NetworkRegion
type CloudNetworkRegion struct {

	// Region Network region
	Region string `json:"region,omitempty"`

	// Status Network region status
	Status string `json:"status,omitempty"`
}
