/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// ContainerObject
type CloudStorageContainerObject struct {

	// Object content type
	ContentType string `json:"contentType,omitempty"`

	// Last modification date
	LastModified time.Time `json:"lastModified,omitempty"`

	// Object name
	Name string `json:"name,omitempty"`

	// Object retrieval delay (when unsealing)
	RetrievalDelay int64 `json:"retrievalDelay,omitempty"`

	// Object retrieval state
	RetrievalState string `json:"retrievalState,omitempty"`

	// Object size
	Size int64 `json:"size,omitempty"`
}
