/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Snapshots usage for current month
type CloudProjectSnapshotsUsage struct {

	// Snapshots usage details
	Detail []CloudProjectSnapshotUsageDetail `json:"detail,omitempty"`

	Total OrderPrice `json:"total,omitempty"`
}
