/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// CloudStorageContainerObject ContainerObject
type CloudStorageContainerObject struct {

	// ContentType Object content type
	ContentType string `json:"contentType,omitempty"`

	// LastModified Last modification date
	LastModified *time.Time `json:"lastModified,omitempty"`

	// Name Object name
	Name string `json:"name,omitempty"`

	// RetrievalDelay Object retrieval delay (when unsealing)
	RetrievalDelay int64 `json:"retrievalDelay,omitempty"`

	// RetrievalState Object retrieval state
	RetrievalState string `json:"retrievalState,omitempty"`

	// Size Object size
	Size int64 `json:"size,omitempty"`
}
