/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Project
type CloudProject struct {

	// Project access
	Access string `json:"access,omitempty"`

	// Project creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Description of your project
	Description string `json:"description,omitempty"`

	// Project order id
	OrderId int64 `json:"orderId,omitempty"`

	// Project id
	ProjectId string `json:"project_id,omitempty"`

	// Current status
	Status string `json:"status,omitempty"`

	// Project unleashed
	Unleash bool `json:"unleash,omitempty"`
}
