/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Details about bandwidth storage pricing
type CloudBandwidthStoragePrice struct {

	Price OrderPrice `json:"price,omitempty"`

	// Bandwidth storage region
	Region string `json:"region,omitempty"`
}
