/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudStorageEndpoint Endpoint
type CloudStorageEndpoint struct {

	// Region Endpoint region
	Region string `json:"region,omitempty"`

	// URL Endpoint URL
	URL string `json:"url,omitempty"`
}
