/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type CloudProjectInstanceBulkPost struct {

	FlavorId string `json:"flavorId,omitempty"`

	GroupId string `json:"groupId,omitempty"`

	ImageId string `json:"imageId,omitempty"`

	MonthlyBilling bool `json:"monthlyBilling,omitempty"`

	Name string `json:"name,omitempty"`

	Networks []CloudInstanceNetworkBulkParams `json:"networks,omitempty"`

	Number int64 `json:"number,omitempty"`

	Region string `json:"region,omitempty"`

	SshKeyId string `json:"sshKeyId,omitempty"`

	UserData string `json:"userData,omitempty"`
}
