/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Instance usage
type CloudProjectInstanceUsageDetail struct {

	Hourly OrderPrice `json:"hourly,omitempty"`

	// Instance id
	InstanceId string `json:"instanceId,omitempty"`

	Monthly CloudProjectInstanceMonthlyBilling `json:"monthly,omitempty"`

	// Is monthly billing enabled
	MonthlyBilling bool `json:"monthlyBilling,omitempty"`

	// Reference
	Reference string `json:"reference,omitempty"`
}
