/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// KeypairQuotas
type CloudQuotaKeypairQuotas struct {

	// Maximum keypairs count allowed in your project
	MaxCount int64 `json:"maxCount,omitempty"`
}
