/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HourlyInstance
type CloudBillingViewHourlyInstance struct {

	// Details about hourly instances
	Details []CloudBillingViewHourlyInstanceDetail `json:"details,omitempty"`

	Quantity CloudBillingViewQuantity `json:"quantity,omitempty"`

	// Instance reference
	Reference string `json:"reference,omitempty"`

	// Instance region
	Region string `json:"region,omitempty"`

	// Total price
	TotalPrice float64 `json:"totalPrice,omitempty"`
}
