/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudProjectNewProject New cloud project
type CloudProjectNewProject struct {

	// Agreements Agreement to valid
	Agreements []int64 `json:"agreements,omitempty"`

	Credit *CloudProjectNewProjectCredit `json:"credit,omitempty"`

	// Description Cloud project description
	Description string `json:"description,omitempty"`

	// OrderID Cloud project order id
	OrderID int64 `json:"orderId,omitempty"`

	// Project Cloud project
	Project string `json:"project,omitempty"`

	// Status Project creation status
	Status string `json:"status,omitempty"`
}
