/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Network
type CloudNetworkNetwork struct {

	// Network id
	Id string `json:"id,omitempty"`

	// Network name
	Name string `json:"name,omitempty"`

	// Details about private network in region
	Regions []CloudNetworkNetworkRegion `json:"regions,omitempty"`

	// Network status
	Status string `json:"status,omitempty"`

	// Network type
	Type_ string `json:"type,omitempty"`

	// Network VLAN id
	VlanId int64 `json:"vlanId,omitempty"`
}
