/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// CloudInstance Instance
type CloudInstance struct {

	// Created Instance creation date
	Created *time.Time `json:"created,omitempty"`

	// FlavorID Instance flavor id
	FlavorID string `json:"flavorId,omitempty"`

	// ID Instance id
	ID string `json:"id,omitempty"`

	// ImageID Instance image id
	ImageID string `json:"imageId,omitempty"`

	// IPAddresses Instance IP addresses
	IPAddresses []*CloudInstanceIPAddress `json:"ipAddresses,omitempty"`

	MonthlyBilling *CloudInstanceMonthlyBilling `json:"monthlyBilling,omitempty"`

	// Name Instance name
	Name string `json:"name,omitempty"`

	// Region Instance id
	Region string `json:"region,omitempty"`

	// SSHKeyID Instance ssh key id
	SSHKeyID string `json:"sshKeyId,omitempty"`

	// Status Instance status
	Status string `json:"status,omitempty"`
}
