/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Instances usage for current month
type CloudProjectInstancesUsage struct {

	// Instance usage details
	Detail []CloudProjectInstanceUsageDetail `json:"detail,omitempty"`

	Total OrderPrice `json:"total,omitempty"`
}
