/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudRegionOpenstackService OpenstackService
type CloudRegionOpenstackService struct {

	// Name Service name
	Name string `json:"name,omitempty"`

	// Status Service status
	Status string `json:"status,omitempty"`
}
