/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// UsedCredit
type CloudBillingViewUsedCredit struct {

	// Credit description
	Description string `json:"description,omitempty"`

	// Credit ID
	Id int64 `json:"id,omitempty"`

	// Total credit used
	UsedAmount float64 `json:"usedAmount,omitempty"`
}
