/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// CloudInstanceDetail InstanceDetail
type CloudInstanceDetail struct {

	// Created Instance creation date
	Created *time.Time `json:"created,omitempty"`

	Flavor *CloudFlavor `json:"flavor,omitempty"`

	// ID Instance id
	ID string `json:"id,omitempty"`

	Image *CloudImage `json:"image,omitempty"`

	// IPAddresses Instance IP addresses
	IPAddresses []*CloudInstanceIPAddress `json:"ipAddresses,omitempty"`

	MonthlyBilling *CloudInstanceMonthlyBilling `json:"monthlyBilling,omitempty"`

	// Name Instance name
	Name string `json:"name,omitempty"`

	// Region Instance id
	Region string `json:"region,omitempty"`

	SSHKey *CloudSSHKeyDetail `json:"sshKey,omitempty"`

	// Status Instance status
	Status string `json:"status,omitempty"`
}
