/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// ProjectForecast
type CloudForecastProjectForecast struct {

	// Time when we got last metric
	LastMetric time.Time `json:"lastMetric,omitempty"`

	ProjectForecast OrderPrice `json:"projectForecast,omitempty"`
}
