/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CloudProjectInstancePost ...
type CloudProjectInstancePost struct {
	FlavorID string `json:"flavorId,omitempty"`

	GroupID string `json:"groupId,omitempty"`

	ImageID string `json:"imageId,omitempty"`

	MonthlyBilling bool `json:"monthlyBilling,omitempty"`

	Name string `json:"name,omitempty"`

	Networks []*CloudInstanceNetworkParams `json:"networks,omitempty"`

	Region string `json:"region,omitempty"`

	SSHKeyID string `json:"sshKeyId,omitempty"`

	UserData string `json:"userData,omitempty"`
}
