/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// ClusterHadoopNetworkAcl ACL for allowing ip blocks to access to your cluster
type ClusterHadoopNetworkAcl struct {

	// Block IP Block to allow
	Block string `json:"block,omitempty"`

	// Description description of this ACL
	Description string `json:"description,omitempty"`

	// State State of the NetworkAcl.
	State string `json:"state,omitempty"`
}
