/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Managed Hadoop Cluster
type ClusterHadoopHadoop struct {

	// CDH and Cloudera Manager version
	ClouderaVersion string `json:"clouderaVersion,omitempty"`

	// Maximum quantity of nodes allowed to be ordered in the cluster
	MaxOrderableNodes int64 `json:"maxOrderableNodes,omitempty"`

	// Service name of your Cluster
	Name string `json:"name,omitempty"`

	// State of the Hadoop Cluster
	State string `json:"state,omitempty"`
}
