/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Detailed information on a node billing profile
type ClusterHadoopNodeBillingProfile struct {

	CPUFrequency ClusterHadoopNodeBillingProfileCpuFrequency `json:"CPUFrequency,omitempty"`

	DiskCapacity ClusterHadoopNodeBillingProfileDiskCapacity `json:"diskCapacity,omitempty"`

	// Total number of the CPU cores
	NbCPUCores int64 `json:"nbCPUCores,omitempty"`

	// Total number of the CPU threads
	NbCPUThreads int64 `json:"nbCPUThreads,omitempty"`

	NetworkBandwidth ClusterHadoopNodeBillingProfileNetworkBandwidth `json:"networkBandwidth,omitempty"`

	// Name of the Node billing profile
	NodeProfile string `json:"nodeProfile,omitempty"`

	RamQuantity ClusterHadoopNodeBillingProfileRamQuantity `json:"ramQuantity,omitempty"`
}
