/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// ClusterHadoopRole Role (ie set of Hadoop services) of the Node
type ClusterHadoopRole struct {

	// ID ID of the Role
	ID int64 `json:"id,omitempty"`

	// TType Role name
	TType string `json:"type,omitempty"`
}
