/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Operation on a Hadoop Cluster component
type ClusterHadoopTask struct {

	// Operation name
	Name string `json:"name,omitempty"`

	// Current Task state
	Status string `json:"status,omitempty"`

	TaskId int64 `json:"taskId,omitempty"`
}
