/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Representation of an Address
type ContactAddress struct {

	// City
	City string `json:"city,omitempty"`

	// Country
	Country string `json:"country,omitempty"`

	// First line of the address
	Line1 string `json:"line1,omitempty"`

	// Second line of the address
	Line2 string `json:"line2,omitempty"`

	// Third line of the address
	Line3 string `json:"line3,omitempty"`

	// Others details
	OtherDetails string `json:"otherDetails,omitempty"`

	// Province name
	Province string `json:"province,omitempty"`

	// Zipcode
	Zip string `json:"zip,omitempty"`
}
