/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaaSLogsURL Web address
type DBaaSLogsURL struct {

	// Address Web URI
	Address string `json:"address,omitempty"`

	// TType Service type
	TType string `json:"type,omitempty"`
}
