/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DBaaSLogsInput Input
type DBaaSLogsInput struct {

	// CreatedAt Input creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Input description
	Description string `json:"description,omitempty"`

	// EngineID Input engine UUID
	EngineID string `json:"engineId,omitempty"`

	// ExposedPort Port
	ExposedPort string `json:"exposedPort,omitempty"`

	// Hostname Hostname
	Hostname string `json:"hostname,omitempty"`

	// InputID Input ID
	InputID string `json:"inputId,omitempty"`

	// OptionID Associated DBaaS Logs option
	OptionID string `json:"optionId,omitempty"`

	// PublicAddress Input IP address
	PublicAddress string `json:"publicAddress,omitempty"`

	// RestartRequired Indicate if input need to be restarted
	RestartRequired bool `json:"restartRequired,omitempty"`

	// SingleInstance Force only one instance
	SingleInstance bool `json:"singleInstance,omitempty"`

	// SSLCertificate Input SSL certificate
	SSLCertificate string `json:"sslCertificate,omitempty"`

	// Status init: configuration required, pending: ready to start, running: available
	Status string `json:"status,omitempty"`

	// StreamID Associated Graylog stream
	StreamID string `json:"streamId,omitempty"`

	// Title Input title
	Title string `json:"title,omitempty"`

	// UpdatedAt Input last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
