/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DBaasLogsDashboard Graylog dashboard
type DBaasLogsDashboard struct {

	// CreatedAt Dashboard creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DashboardID Dashboard UUID
	DashboardID string `json:"dashboardId,omitempty"`

	// Description Dashboard description
	Description string `json:"description,omitempty"`

	// IsEditable Indicates if you are allowed to edit entry
	IsEditable bool `json:"isEditable,omitempty"`

	// OptionID Associated DBaaS Logs option
	OptionID string `json:"optionId,omitempty"`

	// Title Dashboard description
	Title string `json:"title,omitempty"`

	// UpdatedAt Dashboard last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
