/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Graylog role permission
type DBaaSLogsPermission struct {

	// Associated Elasticsearch alias
	AliasId string `json:"aliasId,omitempty"`

	// Associated Graylog dashboard
	DashboardId string `json:"dashboardId,omitempty"`

	// Associated Elasticsearch index
	IndexId string `json:"indexId,omitempty"`

	// Permission UUID
	PermissionId string `json:"permissionId,omitempty"`

	// Associated Graylog stream
	StreamId string `json:"streamId,omitempty"`
}
