/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaasLogsPermission Graylog role permission
type DBaasLogsPermission struct {

	// AliasID Associated Elasticsearch alias
	AliasID string `json:"aliasId,omitempty"`

	// DashboardID Associated Graylog dashboard
	DashboardID string `json:"dashboardId,omitempty"`

	// IndexID Associated Elasticsearch index
	IndexID string `json:"indexId,omitempty"`

	// PermissionID Permission UUID
	PermissionID string `json:"permissionId,omitempty"`

	// StreamID Associated Graylog stream
	StreamID string `json:"streamId,omitempty"`
}
