/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Elasticsearch alias
type DBaaSLogsAlias struct {

	// Alias UUID
	AliasId string `json:"aliasId,omitempty"`

	// Input creation
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Alias description
	Description string `json:"description,omitempty"`

	// Indicates if you are allowed to edit entry
	IsEditable bool `json:"isEditable,omitempty"`

	// Alias name
	Name string `json:"name,omitempty"`

	// Associated DBaaS Logs option
	OptionId string `json:"optionId,omitempty"`

	// Input last update
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
