/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaaSLogsEngine Input engine
type DBaaSLogsEngine struct {

	// EngineID Input engine UUID
	EngineID string `json:"engineId,omitempty"`

	// IsDeprecated Indicates if engine will soon not be supported
	IsDeprecated bool `json:"isDeprecated,omitempty"`

	// Name Software name
	Name string `json:"name,omitempty"`

	// Version Software version
	Version string `json:"version,omitempty"`
}
