/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DBaasLogsIndex Elasticsearch index
type DBaasLogsIndex struct {

	// CreatedAt Index creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Index description
	Description string `json:"description,omitempty"`

	// IndexID Index UUID
	IndexID string `json:"indexId,omitempty"`

	// IsEditable Indicates if you are allowed to edit entry
	IsEditable bool `json:"isEditable,omitempty"`

	// Name Index name
	Name string `json:"name,omitempty"`

	// OptionID Associated DBaaS Logs option
	OptionID string `json:"optionId,omitempty"`

	// UpdatedAt Index last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
