/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaasLogsFlowggerConfiguration Flowgger configuration
type DBaasLogsFlowggerConfiguration struct {

	// KafkaCoalesce Number of message to always waits for a full batch to be         buffered before sending it to Kafka
	KafkaCoalesce int64 `json:"kafkaCoalesce,omitempty"`

	// LogFormat Type of format to decode
	LogFormat string `json:"logFormat,omitempty"`

	// LogFraming Indicates how messages are splitted
	LogFraming string `json:"logFraming,omitempty"`

	// TLSMethod TLS version
	TLSMethod string `json:"tlsMethod,omitempty"`

	// TType Input type
	TType string `json:"type,omitempty"`
}
