/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DBaasLogsOperation Input operation
type DBaasLogsOperation struct {

	// AliasID Alias used
	AliasID string `json:"aliasId,omitempty"`

	// CreatedAt Operation creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DashboardID Dashboard used
	DashboardID string `json:"dashboardId,omitempty"`

	// IndexID Index used
	IndexID string `json:"indexId,omitempty"`

	// InputID Input used
	InputID string `json:"inputId,omitempty"`

	// OperationID Operation UUID
	OperationID string `json:"operationId,omitempty"`

	// RoleID Role used
	RoleID string `json:"roleId,omitempty"`

	// State Operation status
	State string `json:"state,omitempty"`

	// StreamID Stream used
	StreamID string `json:"streamId,omitempty"`

	// UpdatedAt Operation last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
