/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaasTimeseriesSetupPost ...
type DBaasTimeseriesSetupPost struct {
	Description string `json:"description,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	RaTokenID string `json:"raTokenId,omitempty"`

	RaTokenKey string `json:"raTokenKey,omitempty"`

	RegionID string `json:"regionId,omitempty"`
}
