/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DbaasQueueRolePost struct {

	AutoCreateAcl bool `json:"autoCreateAcl,omitempty"`

	Name string `json:"name,omitempty"`

	ReadAcl []string `json:"readAcl,omitempty"`

	WriteAcl []string `json:"writeAcl,omitempty"`
}
