/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DbaasQueueTopicPost struct {

	Id string `json:"id,omitempty"`

	Partitions int64 `json:"partitions,omitempty"`

	ReplicationFactor int64 `json:"replicationFactor,omitempty"`
}
