/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DbaasQueueRegion Region
type DbaasQueueRegion struct {

	// ID Region ID
	ID string `json:"id,omitempty"`

	// Name Region name
	Name string `json:"name,omitempty"`

	// URL Region URL
	URL string `json:"url,omitempty"`
}
