/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// User
type DbaasQueueUser struct {

	// User ID
	Id string `json:"id,omitempty"`

	// User name
	Name string `json:"name,omitempty"`

	// List of roles this user belongs to
	Roles []string `json:"roles,omitempty"`
}
