/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Topic
type DbaasQueueTopic struct {

	// Topic ID
	Id string `json:"id,omitempty"`

	// Number of partitions
	Partitions int64 `json:"partitions,omitempty"`

	// Replication factor
	ReplicationFactor int64 `json:"replicationFactor,omitempty"`
}
