/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Region
type DbaasQueueRegion struct {

	// Region ID
	Id string `json:"id,omitempty"`

	// Region name
	Name string `json:"name,omitempty"`

	// Region URL
	Url string `json:"url,omitempty"`
}
