/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DbaasLogsInputConfigurationLogstashPut struct {

	FilterSection string `json:"filterSection,omitempty"`

	InputSection string `json:"inputSection,omitempty"`

	PatternSection string `json:"patternSection,omitempty"`
}
