/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DBaasQueueRole Role
type DBaasQueueRole struct {

	// AutoCreateAcl Automatically create non-existing topics on read & write operations
	AutoCreateAcl bool `json:"autoCreateAcl,omitempty"`

	// Name Role name
	Name string `json:"name,omitempty"`

	// ReadAcl List of topics with read access
	ReadAcl []string `json:"readAcl,omitempty"`

	// WriteAcl List of topics with write access
	WriteAcl []string `json:"writeAcl,omitempty"`
}
