/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// State of a debt
type DebtDebt struct {

	Amount OrderPrice `json:"amount,omitempty"`

	// Date the debt was created on
	Date time.Time `json:"date,omitempty"`

	DebtId int64 `json:"debtId,omitempty"`

	DueAmount OrderPrice `json:"dueAmount,omitempty"`

	// If specified, the debt will not be recovered before that date
	DueDate time.Time `json:"dueDate,omitempty"`

	// The order the debt relates to
	OrderId int64 `json:"orderId,omitempty"`

	PendingAmount OrderPrice `json:"pendingAmount,omitempty"`

	TodoAmount OrderPrice `json:"todoAmount,omitempty"`

	UnmaturedAmount OrderPrice `json:"unmaturedAmount,omitempty"`
}
