/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerHardwareSpecificationsDisk A structure describing informations about server disks
type DedicatedServerHardwareSpecificationsDisk struct {

	// Description human readable description of this disk group
	Description string `json:"description,omitempty"`

	// DiskGroupID identifier of this disk group
	DiskGroupID int64 `json:"diskGroupId,omitempty"`

	DiskSize *DedicatedServerHardwareSpecificationsDiskDiskSize `json:"diskSize,omitempty"`

	// DiskType type of the disk (SSD, SATA, SAS, ...)
	DiskType string `json:"diskType,omitempty"`

	// NumberOfDisks number of disks in this group
	NumberOfDisks int64 `json:"numberOfDisks,omitempty"`

	// RaidController raid controller, if any, managing this group of disks
	RaidController string `json:"raidController,omitempty"`
}
