/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

//  Partitions defined in this partitioning scheme
type DedicatedInstallationTemplateTemplatePartitions struct {

	// Partition filesytem
	Filesystem string `json:"filesystem,omitempty"`

	// partition mount point
	Mountpoint string `json:"mountpoint,omitempty"`

	// specifies the creation order of the partition on the disk
	Order int64 `json:"order,omitempty"`

	// raid partition type
	Raid string `json:"raid,omitempty"`

	Size DedicatedInstallationTemplateTemplatePartitionsSize `json:"size,omitempty"`

	Type_ string `json:"type,omitempty"`

	// The volume name needed for proxmox distribution
	VolumeName string `json:"volumeName,omitempty"`
}
