/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DedicatedServerFeaturesIpmiAccessPost struct {

	IpToAllow string `json:"ipToAllow,omitempty"`

	SshKey string `json:"sshKey,omitempty"`

	Ttl int64 `json:"ttl,omitempty"`

	Type_ string `json:"type,omitempty"`
}
