/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Storage nas
type DedicatedNasNas struct {

	// True, if partition creation is allowed on this nas
	CanCreatePartition bool `json:"canCreatePartition,omitempty"`

	// The name you give to the nas
	CustomName string `json:"customName,omitempty"`

	// area of nas
	Datacenter string `json:"datacenter,omitempty"`

	// Access ip of nas
	Ip string `json:"ip,omitempty"`

	// The storage mount path
	MountPath string `json:"mountPath,omitempty"`

	// The storage service name
	ServiceName string `json:"serviceName,omitempty"`

	// the size of the nas
	ZpoolSize int64 `json:"zpoolSize,omitempty"`
}
