/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerNetbootOption Available boot options
type DedicatedServerNetbootOption struct {

	// Option The option of this boot
	Option string `json:"option,omitempty"`

	// Value the value of this option
	Value string `json:"value,omitempty"`
}
