/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing network informations about this dedicated server
type DedicatedServerNetworkSpecifications struct {

	Bandwidth DedicatedServerBandwidthDetails `json:"bandwidth,omitempty"`

	Connection DedicatedServerNetworkSpecificationsConnection `json:"connection,omitempty"`

	Traffic DedicatedServerTrafficDetails `json:"traffic,omitempty"`
}
