/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// A structure describing ipmi access value
type DedicatedServerIpmiAccessValue struct {

	// Session expiration date
	Expiration time.Time `json:"expiration,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}
