/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerRtmDiskSmart A structure describing SMART health disk status
type DedicatedServerRtmDiskSmart struct {

	// CurrentPendingSector Current pending sectors
	CurrentPendingSector int64 `json:"current_pending_sector,omitempty"`

	// MultizoneErrorRate Multizone error rate
	MultizoneErrorRate int64 `json:"multizone_error_rate,omitempty"`

	// OfflineSeekPerformance Offline seek rate
	OfflineSeekPerformance int64 `json:"offline_seek_performance,omitempty"`

	// OfflineUncorrectable Offline uncorrectable
	OfflineUncorrectable int64 `json:"offline_uncorrectable,omitempty"`

	// OtherErrors Other errors
	OtherErrors int64 `json:"other_errors,omitempty"`

	// RealocatedEventCount Realocated event count
	RealocatedEventCount int64 `json:"realocated_event_count,omitempty"`

	// TemperatureCelsius temperature
	TemperatureCelsius int64 `json:"temperature_celsius,omitempty"`

	// UdmaCrcError UDMA crc error
	UdmaCrcError int64 `json:"udma_crc_error,omitempty"`

	// UncorrectedReadErrors Uncorrected read errors
	UncorrectedReadErrors int64 `json:"uncorrected_read_errors,omitempty"`

	// UncorrectedWriteErrors Uncorrected write errors
	UncorrectedWriteErrors int64 `json:"uncorrected_write_errors,omitempty"`
}
