/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerNetboot Available boots
type DedicatedServerNetboot struct {

	// BootID boot id
	BootID int64 `json:"bootId,omitempty"`

	// BootType the boot system
	BootType string `json:"bootType,omitempty"`

	// Description the boot description
	Description string `json:"description,omitempty"`

	// Kernel The boot kernel
	Kernel string `json:"kernel,omitempty"`
}
