/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Intervention made on this server
type DedicatedServerIntervention struct {

	// the intervention start date
	Date time.Time `json:"date,omitempty"`

	// The intervention id
	InterventionId int64 `json:"interventionId,omitempty"`

	// the intervention type
	Type_ string `json:"type,omitempty"`
}
