/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing informations about installation custom
type DedicatedServerInstallCustom struct {

	// Personnal hostname to use in server reinstallation
	CustomHostname string `json:"customHostname,omitempty"`

	// Disk group id to process install on (only available for some templates)
	DiskGroupId int64 `json:"diskGroupId,omitempty"`

	// true if you want to install windows with sql feature
	InstallSqlServer bool `json:"installSqlServer,omitempty"`

	// install language for ovh install choice
	Language string `json:"language,omitempty"`

	// true if you want to install only on the first disk
	NoRaid bool `json:"noRaid,omitempty"`

	// the url to your custom install script
	PostInstallationScriptLink string `json:"postInstallationScriptLink,omitempty"`

	//  the return of your script if everythings ok. Advice: your script should return a unique validation string in case of succes. A good example is \"loh1Xee7eo OK OK OK UGh8Ang1Gu
	PostInstallationScriptReturn string `json:"postInstallationScriptReturn,omitempty"`

	// Number of devices to use for system's software RAID
	SoftRaidDevices int64 `json:"softRaidDevices,omitempty"`

	// The name of ssh key to install
	SshKeyName string `json:"sshKeyName,omitempty"`

	// true if you want to install with distrib kernel
	UseDistribKernel bool `json:"useDistribKernel,omitempty"`

	// true if you want to install windows with your spla license
	UseSpla bool `json:"useSpla,omitempty"`
}
