/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedNasQuota Partition Quota
type DedicatedNasQuota struct {

	// Size the size to set in MB
	Size int64 `json:"size,omitempty"`

	// UID the uid to set quota on
	UID int64 `json:"uid,omitempty"`
}
