/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerVirtualMacManagement  ip address linked with this virtual mac address
type DedicatedServerVirtualMacManagement struct {

	// IPAddress IP address
	IPAddress string `json:"ipAddress,omitempty"`

	// VirtualMachineName Friendly name of your Virtual Machine behind this IP/MAC
	VirtualMachineName string `json:"virtualMachineName,omitempty"`
}
