/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudRight Dedicated Cloud User right
type DedicatedCloudRight struct {

	// CanAddRessource Determine if the user can add ressources in your Dedicated Cloud
	CanAddRessource bool `json:"canAddRessource,omitempty"`

	DatacenterID int64 `json:"datacenterId,omitempty"`

	// NetworkRole Determine how this user can interact with the Dedicated Cloud V(x)Lans
	NetworkRole string `json:"networkRole,omitempty"`

	// Right Determine what kind of access the User will have in this Datacenter of your Dedicated Cloud
	Right string `json:"right,omitempty"`

	RightID int64 `json:"rightId,omitempty"`

	// VMNetworkRole Determine how this user can interact with the Dedicated Cloud VM Network
	VMNetworkRole string `json:"vmNetworkRole,omitempty"`
}
