/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Server informations
type DedicatedServerDedicated struct {

	BootId int64 `json:"bootId,omitempty"`

	// dedicater server commercial range
	CommercialRange string `json:"commercialRange,omitempty"`

	// dedicated datacenter localisation
	Datacenter string `json:"datacenter,omitempty"`

	// dedicated server ip
	Ip string `json:"ip,omitempty"`

	LinkSpeed int64 `json:"linkSpeed,omitempty"`

	// Icmp monitoring state
	Monitoring bool `json:"monitoring,omitempty"`

	// dedicated server name
	Name string `json:"name,omitempty"`

	// Operating system
	Os string `json:"os,omitempty"`

	// Does this server have professional use option
	ProfessionalUse bool `json:"professionalUse,omitempty"`

	Rack string `json:"rack,omitempty"`

	RescueMail string `json:"rescueMail,omitempty"`

	// dedicated server reverse
	Reverse string `json:"reverse,omitempty"`

	RootDevice string `json:"rootDevice,omitempty"`

	// your server id
	ServerId int64 `json:"serverId,omitempty"`

	State string `json:"state,omitempty"`

	// Dedicated server support level
	SupportLevel string `json:"supportLevel,omitempty"`
}
