/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerHardwareRaidController RAID controller configuration
type DedicatedServerHardwareRaidController struct {

	// Disks Connected disk type
	Disks []*DedicatedServerHardwareRaidDiskGroup `json:"disks,omitempty"`

	// Model Raid controler model
	Model string `json:"model,omitempty"`

	// TType Raid controler type
	TType string `json:"type,omitempty"`
}
