/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerUsbKeyOrderableDetails A structure describing informations about orderable USB keys
type DedicatedServerUsbKeyOrderableDetails struct {

	// Capacity Orderable USB keys capacity in gigabytes
	Capacity []int64 `json:"capacity,omitempty"`

	// Number Number of USB keys that can be ordered for this server
	Number int64 `json:"number,omitempty"`

	// OptionRequired Which option is required to order an USB key
	OptionRequired string `json:"optionRequired,omitempty"`

	// Orderable Is USB keys orderable for this server
	Orderable bool `json:"orderable,omitempty"`
}
