/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Available boots
type DedicatedServerNetboot struct {

	// boot id
	BootId int64 `json:"bootId,omitempty"`

	// the boot system
	BootType string `json:"bootType,omitempty"`

	// the boot description
	Description string `json:"description,omitempty"`

	// The boot kernel
	Kernel string `json:"kernel,omitempty"`
}
