/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Private Cloud Restore Point
type DedicatedCloudRestorePoint struct {

	// Creation time of the restore point
	CreationTime string `json:"creationTime,omitempty"`

	// Show if the restore point is corrupted
	IsCorrupted bool `json:"isCorrupted,omitempty"`

	// Id of the restore point.
	RestorePointId int64 `json:"restorePointId,omitempty"`

	RestorePointSize DedicatedCloudRestorePointRestorePointSize `json:"restorePointSize,omitempty"`

	// Type of the restore point
	Type_ string `json:"type,omitempty"`
}
