/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DedicatedCephUserPoolPut struct {

	ClassRead bool `json:"classRead,omitempty"`

	ClassWrite bool `json:"classWrite,omitempty"`

	Execute bool `json:"execute,omitempty"`

	PoolName string `json:"poolName,omitempty"`

	Read bool `json:"read,omitempty"`

	Write bool `json:"write,omitempty"`
}
