/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DedicatedCloudUserPost struct {

	CanAddRessource bool `json:"canAddRessource,omitempty"`

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`

	NetworkRole string `json:"networkRole,omitempty"`

	Password string `json:"password,omitempty"`

	Right string `json:"right,omitempty"`

	VmNetworkRole string `json:"vmNetworkRole,omitempty"`
}
