/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudIP IP Blocks associated with a Dedicated Cloud
type DedicatedCloudIP struct {
	Country string `json:"country,omitempty"`

	Description string `json:"description,omitempty"`

	// Network IP ex: 213.186.33.34/24
	Network string `json:"network,omitempty"`

	// NetworkName Network name
	NetworkName string `json:"networkName,omitempty"`

	// Register The Regional Internet Registry of this Ip Block
	Register string `json:"register,omitempty"`

	// VlanNumber Vlan where this network is routed
	VlanNumber int64 `json:"vlanNumber,omitempty"`
}
