/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DedicatedServerSplaPost struct {

	SerialNumber string `json:"serialNumber,omitempty"`

	Type_ string `json:"type,omitempty"`
}
