/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing the Resource's new price
type DedicatedCloudResourceNewPrices struct {

	Resources []DedicatedCloudResourceNewPricesEntry `json:"resources,omitempty"`
}
