/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudRobot The robots used in Dedicated Cloud
type DedicatedCloudRobot struct {

	// Criticity The criticity of this robot
	Criticity string `json:"criticity,omitempty"`

	// Description Description of this robot
	Description string `json:"description,omitempty"`

	// Enabled Is this robot enabled
	Enabled bool `json:"enabled,omitempty"`

	// Name The name of this robot
	Name string `json:"name,omitempty"`

	// TType The type of this robot
	TType string `json:"type,omitempty"`
}
