/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedHousingLinkInfo A structure describing the Bay`s link information
type DedicatedHousingLinkInfo struct {

	// Port Router port number
	Port string `json:"port,omitempty"`

	// Router Router in charge of your network
	Router string `json:"router,omitempty"`
}
