/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing informations bandwidth orderable for this dedicated server
type DedicatedServerBandwidthOrderable struct {

	// Is bandwidth orderable for this server
	Orderable bool `json:"orderable,omitempty"`

	// Bandwidth \"platinum\" orderable in mbps
	Platinum []int64 `json:"platinum,omitempty"`

	// Bandwidth \"premium\" orderable in mbps
	Premium []int64 `json:"premium,omitempty"`

	// Bandwidth \"ultimate\" orderable in mbps
	Ultimate []int64 `json:"ultimate,omitempty"`
}
