/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerHardwareRaidProfile A structure describing the server's hardware RAID configuration
type DedicatedServerHardwareRaidProfile struct {

	// Controllers Hardware RAID controller list
	Controllers []*DedicatedServerHardwareRaidController `json:"controllers,omitempty"`
}
