/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Hardware RAID defined in this partitioning scheme
type DedicatedInstallationTemplateHardwareRaid struct {

	// Disk list
	Disks []string `json:"disks,omitempty"`

	// RAID mode
	Mode string `json:"mode,omitempty"`

	// Hardware RAID name
	Name string `json:"name,omitempty"`

	// Specifies the creation order of the hardware RAID
	Step int64 `json:"step,omitempty"`
}
