/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing informations about server cpu
type DedicatedServerRtmCpu struct {

	Cache DedicatedServerRtmCpuCache `json:"cache,omitempty"`

	// CPU core number
	Core int64 `json:"core,omitempty"`

	Freq DedicatedServerRtmCpuFreq `json:"freq,omitempty"`

	// CPU  name
	Name string `json:"name,omitempty"`
}
