/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerRtmRaidVolume Server raid volume information
type DedicatedServerRtmRaidVolume struct {
	Capacity *DedicatedServerRtmRaidVolumeCapacity `json:"capacity,omitempty"`

	// Chunks Raid volume chunks
	Chunks string `json:"chunks,omitempty"`

	// Label Raid volume label
	Label string `json:"label,omitempty"`

	// Letter Raid volume letter
	Letter string `json:"letter,omitempty"`

	// Phys Raid volume phys
	Phys string `json:"phys,omitempty"`

	// Status Raid volume status
	Status string `json:"status,omitempty"`

	// Stripe Raid volume stripe
	Stripe string `json:"stripe,omitempty"`

	// Syncprogress Raid volume synchronization progress
	Syncprogress string `json:"syncprogress,omitempty"`

	// TType Raid volume type
	TType string `json:"type,omitempty"`

	// Volume Raid volume name
	Volume string `json:"volume,omitempty"`
}
