/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedNashaSnapshot Partition Snapshot
type DedicatedNashaSnapshot struct {

	// SnapshotType the interval of snapshot
	SnapshotType string `json:"snapshotType,omitempty"`
}
