/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedServerServiceMonitoring Service monitoring details
type DedicatedServerServiceMonitoring struct {

	// ChallengeText The expected return
	ChallengeText string `json:"challengeText,omitempty"`

	// Enabled Is this service monitoring is enabled
	Enabled bool `json:"enabled,omitempty"`

	// Interval The test interval in seconds
	Interval string `json:"interval,omitempty"`

	// IP The ip to monitor
	IP string `json:"ip,omitempty"`

	// MonitoringID This monitoring id
	MonitoringID int64 `json:"monitoringId,omitempty"`

	// Port The service port to monitor
	Port int64 `json:"port,omitempty"`

	// Protocol The protocol to use
	Protocol string `json:"protocol,omitempty"`

	// URL The URL to test
	URL string `json:"url,omitempty"`
}
