/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudVMFiler A structure describing filers of a the virtual machine
type DedicatedCloudVMFiler struct {
	Committed float64 `json:"committed,omitempty"`

	Disks []*DedicatedCloudVMFilerDisk `json:"disks,omitempty"`

	Name string `json:"name,omitempty"`
}
