/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DedicatedServerIntervention Intervention made on this server
type DedicatedServerIntervention struct {

	// Date the intervention start date
	Date *time.Time `json:"date,omitempty"`

	// InterventionID The intervention id
	InterventionID int64 `json:"interventionId,omitempty"`

	// TType the intervention type
	TType string `json:"type,omitempty"`
}
