/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Server disks informations
type DedicatedServerRtmDisk struct {

	Capacity DedicatedServerHardwareRaidConfigurationDiskSize `json:"capacity,omitempty"`

	// Disk
	Disk string `json:"disk,omitempty"`

	// Disk model
	Model string `json:"model,omitempty"`

	Temperature DedicatedServerRtmDiskTemperature `json:"temperature,omitempty"`
}
