/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudHostProfile A Host profile
type DedicatedCloudHostProfile struct {
	Core string `json:"core,omitempty"`

	CPU *DedicatedServerMrtgTimestampValueValue `json:"cpu,omitempty"`

	Name string `json:"name,omitempty"`

	RAM *DedicatedCloudFilerProfileSize `json:"ram,omitempty"`
}
