/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// SPLA licenses management
type DedicatedServerSpla struct {

	// License id
	Id int64 `json:"id,omitempty"`

	// Last update timestamp
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// License serial number
	SerialNumber string `json:"serialNumber,omitempty"`

	// Status of license
	Status string `json:"status,omitempty"`

	// License type
	Type_ string `json:"type,omitempty"`
}
