/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedNashaStorage Storage nas HA
type DedicatedNashaStorage struct {

	// CanCreatePartition True, if partition creation is allowed on this nas HA
	CanCreatePartition bool `json:"canCreatePartition,omitempty"`

	// CustomName The name you give to the nas
	CustomName string `json:"customName,omitempty"`

	// Datacenter area of nas
	Datacenter string `json:"datacenter,omitempty"`

	// IP Access ip of nas
	IP string `json:"ip,omitempty"`

	// Monitored Send an email to customer if any issue is detected
	Monitored bool `json:"monitored,omitempty"`

	// ServiceName The storage service name
	ServiceName string `json:"serviceName,omitempty"`

	// ZpoolCapacity percentage of nas space used in %
	ZpoolCapacity int64 `json:"zpoolCapacity,omitempty"`

	// ZpoolSize the size of the nas
	ZpoolSize int64 `json:"zpoolSize,omitempty"`
}
