/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing the Bay`s network configuration
type DedicatedHousingNetworkInfo struct {

	Ipv4 DedicatedHousingIpInfo `json:"ipv4,omitempty"`

	Ipv6 DedicatedHousingIpInfo `json:"ipv6,omitempty"`

	Link DedicatedHousingLinkInfo `json:"link,omitempty"`
}
