/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type DedicatedCloudAllowedNetworkPost struct {

	Description string `json:"description,omitempty"`

	Network string `json:"network,omitempty"`
}
