/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing the backing network of a the virtual machine
type DedicatedCloudVmNetworkBacking struct {

	DeviceName string `json:"deviceName,omitempty"`

	PortGroupKey string `json:"portGroupKey,omitempty"`

	PortKey string `json:"portKey,omitempty"`

	SwitchUuid string `json:"switchUuid,omitempty"`

	Type_ string `json:"type,omitempty"`

	UseAutoDetect bool `json:"useAutoDetect,omitempty"`

	ValueMoref string `json:"valueMoref,omitempty"`
}
