/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedNashaPartition Storage zpool partition
type DedicatedNashaPartition struct {

	// PartitionCapacity percentage of partition space used in %
	PartitionCapacity int64 `json:"partitionCapacity,omitempty"`

	// PartitionName the given name of partition
	PartitionName string `json:"partitionName,omitempty"`

	// Protocol must be nfs cifs or both
	Protocol string `json:"protocol,omitempty"`

	// Size Partition size
	Size int64 `json:"size,omitempty"`

	// UsedBySnapshots percentage of partition space used by snapshots, in %
	UsedBySnapshots int64 `json:"usedBySnapshots,omitempty"`
}
