/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudFilerProfile A Filer profile
type DedicatedCloudFilerProfile struct {

	// FullName Human-Readable name
	FullName string `json:"fullName,omitempty"`

	// Name Commercial name
	Name string `json:"name,omitempty"`

	Size *DedicatedCloudFilerProfileSize `json:"size,omitempty"`
}
