/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudVM Dedicated Cloud Virtual Machine
type DedicatedCloudVM struct {

	// ClusterName Cluster of the virtual machine.
	ClusterName string `json:"clusterName,omitempty"`

	// CPUMax Maximum CPU performance, in MHz.
	CPUMax float64 `json:"cpuMax,omitempty"`

	// CPUNum Number of processors in the virtual machine.
	CPUNum int64 `json:"cpuNum,omitempty"`

	// CPUReady Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU. In millisecond
	CPUReady float64 `json:"cpuReady,omitempty"`

	// CPUReadyPercent Percentage of time that the virtual machine was ready, but could not get scheduled to run on the physical CPU. In percent
	CPUReadyPercent float64 `json:"cpuReadyPercent,omitempty"`

	// CPUUsed Current CPU performance, in MHz.
	CPUUsed int64 `json:"cpuUsed,omitempty"`

	// Filers List of filers in use by the virtual machine.
	Filers []*DedicatedCloudVMFiler `json:"filers,omitempty"`

	// FolderName Folder of the virtual machine.
	FolderName string `json:"folderName,omitempty"`

	// HostName Name of the host hosting the virtual machine.
	HostName string `json:"hostName,omitempty"`

	// MemoryMax Memory size of the virtual machine, in MB
	MemoryMax int64 `json:"memoryMax,omitempty"`

	// MemoryTps Amount of guest memory that is shared with other virtual machines, in Mb
	MemoryTps string `json:"memoryTps,omitempty"`

	// MemoryUsed Current memory utilization, in MB
	MemoryUsed int64 `json:"memoryUsed,omitempty"`

	// MoRef moRef of the virtual machine.
	MoRef string `json:"moRef,omitempty"`

	// Name Name of the virtual machine.
	Name string `json:"name,omitempty"`

	// NetPacketRx Number of packets received.
	NetPacketRx float64 `json:"netPacketRx,omitempty"`

	// NetPacketTx Number of packets transmitted.
	NetPacketTx float64 `json:"netPacketTx,omitempty"`

	// NetRx Rate at which data is received. In KB/s
	NetRx float64 `json:"netRx,omitempty"`

	// NetTx Rate at which data is transmitted. In KB/s
	NetTx float64 `json:"netTx,omitempty"`

	// Networks List of the networks link to this virtual machine
	Networks []*DedicatedCloudVMNetwork `json:"networks,omitempty"`

	// PowerState Power state of the virtual machine.
	PowerState string `json:"powerState,omitempty"`

	// ReadLatency Amount of time for a read operation from the virtual disk. In millisecond
	ReadLatency float64 `json:"readLatency,omitempty"`

	// ReadPerSecond Number of read issued per second to the virtual disk. In millisecond
	ReadPerSecond float64 `json:"readPerSecond,omitempty"`

	// ReadRate Rate of reading data from the virtual disk. In KB/s
	ReadRate float64 `json:"readRate,omitempty"`

	// RoleFt The index of the current VM in instanceUuids array starting from 1, so 1 means that it is the primary VM.
	RoleFt string `json:"roleFt,omitempty"`

	// SnapshotNum Number of snapshot of the virtual machine.
	SnapshotNum int64 `json:"snapshotNum,omitempty"`

	// StateFt The fault tolerance state of the virtual machine.
	StateFt string `json:"stateFt,omitempty"`

	// VMID Id of the virtual machine.
	VMID int64 `json:"vmId,omitempty"`

	// VMwareTools Current version status of VMware Tools in the guest operating system.
	VMwareTools string `json:"vmwareTools,omitempty"`

	// VMwareToolsVersion Current version of VMware Tools
	VMwareToolsVersion string `json:"vmwareToolsVersion,omitempty"`

	// WriteLatency Amount of time for a write operation from the virtual disk. In millisecond
	WriteLatency float64 `json:"writeLatency,omitempty"`

	// WritePerSecond Number of write issued per second to the virtual disk. In millisecond
	WritePerSecond float64 `json:"writePerSecond,omitempty"`

	// WriteRate Rate of writing data from the virtual disk. In KB/s
	WriteRate float64 `json:"writeRate,omitempty"`
}
