/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Partitioning schemes available on this template
type DedicatedInstallationTemplateTemplatePartitioningSchemes struct {

	// name of this partitioning scheme
	Name string `json:"name,omitempty"`

	// on a reinstall, if a partitioning scheme is not specified, the one with the higher priority will be used by default, among all the compatible partitioning schemes (given the underlying hardware specifications)
	Priority int64 `json:"priority,omitempty"`
}
