/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloud Dedicated Cloud
type DedicatedCloud struct {

	// Bandwidth The current bandwidth of your Dedicated Cloud
	Bandwidth string `json:"bandwidth,omitempty"`

	// BillingType Billing type of your Dedicated Cloud
	BillingType string `json:"billingType,omitempty"`

	// CommercialRange The current version of your Dedicated Cloud
	CommercialRange string `json:"commercialRange,omitempty"`

	// Description Description of your Dedicated Cloud
	Description string `json:"description,omitempty"`

	// Location Datacenter where your Dedicated Cloud is physically located
	Location string `json:"location,omitempty"`

	// ManagementInterface The management interface name
	ManagementInterface string `json:"managementInterface,omitempty"`

	// ServiceName Service name of your Dedicated Cloud
	ServiceName string `json:"serviceName,omitempty"`

	// Spla SPLA licensing state
	Spla bool `json:"spla,omitempty"`

	// SSLV3 Enable SSL v3 support. Warning : this option is not recommended as it was recognized as a security breach. If this is enabled, we advise you to enable the filtered User access policy
	SSLV3 bool `json:"sslV3,omitempty"`

	// State Current state of your Dedicated Cloud
	State string `json:"state,omitempty"`

	// UserAccessPolicy Access policy of your Dedicated Cloud : opened to every IPs or filtered
	UserAccessPolicy string `json:"userAccessPolicy,omitempty"`

	// UserLimitConcurrentSession The maximum amount of connected users allowed on the Dedicated Cloud management interface
	UserLimitConcurrentSession int64 `json:"userLimitConcurrentSession,omitempty"`

	UserLogoutPolicy string `json:"userLogoutPolicy,omitempty"`

	// UserSessionTimeout The timeout (in seconds) for the user sessions on the Dedicated Cloud management interface. 0 value disable the timeout
	UserSessionTimeout int64 `json:"userSessionTimeout,omitempty"`

	// VScopeURL Url to the vScope associated to this Dedicated Cloud
	VScopeURL string `json:"vScopeUrl,omitempty"`

	Version *DedicatedCloudVersion `json:"version,omitempty"`
}
