/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing filer disks of a the virtual machine
type DedicatedCloudVmFilerDisk struct {

	Capacity float64 `json:"capacity,omitempty"`

	Id string `json:"id,omitempty"`
}
