/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Housing bay
type DedicatedHousingHousing struct {

	// Housing bay datacenter
	Datacenter string `json:"datacenter,omitempty"`

	// The name you give to the bay
	Name string `json:"name,omitempty"`

	// Housing bay network
	Network []DedicatedHousingNetworkInfo `json:"network,omitempty"`

	Options DedicatedHousingOptions `json:"options,omitempty"`

	// The bay's description
	Rack string `json:"rack,omitempty"`

	// Bay Security code
	SecurityCode string `json:"securityCode,omitempty"`
}
