/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedHousingFeaturesBackupFtpAccessPost ...
type DedicatedHousingFeaturesBackupFtpAccessPost struct {
	Cifs bool `json:"cifs,omitempty"`

	Ftp bool `json:"ftp,omitempty"`

	IPBlock string `json:"ipBlock,omitempty"`

	Nfs bool `json:"nfs,omitempty"`
}
