/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DedicatedCloudUser Dedicated Cloud User
type DedicatedCloudUser struct {
	ActivationState string `json:"activationState,omitempty"`

	CanManageIPFailOvers bool `json:"canManageIpFailOvers,omitempty"`

	CanManageNetwork bool `json:"canManageNetwork,omitempty"`

	Email string `json:"email,omitempty"`

	FullAdminRo bool `json:"fullAdminRo,omitempty"`

	// IsEnableManageable Check if the given Dedicated Cloud user can be enabled or disabled ?
	IsEnableManageable bool `json:"isEnableManageable,omitempty"`

	Name string `json:"name,omitempty"`

	State string `json:"state,omitempty"`

	UserID int64 `json:"userId,omitempty"`
}
