/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Desktop As A Service
type DeskaasDeskaas struct {

	// Alias determined by the use
	Alias string `json:"alias,omitempty"`

	DataDisk DeskaasDeskaasDataDisk `json:"dataDisk,omitempty"`

	// Outgoing ip
	Ip string `json:"ip,omitempty"`

	// Operating system of desktop
	Os string `json:"os,omitempty"`

	// Profile of Virtual Desktop
	PlanCode string `json:"planCode,omitempty"`

	Ram DeskaasDeskaasRam `json:"ram,omitempty"`

	// Reference of Virtual Desktop
	Reference string `json:"reference,omitempty"`

	// Service name of your Desktop As A Service
	ServiceName string `json:"serviceName,omitempty"`

	// Current state of your Virtual Desktop
	State string `json:"state,omitempty"`

	// URL to connect to the virtualDesktop
	Url string `json:"url,omitempty"`

	// Vcpu allocated to desktop
	Vcpu int64 `json:"vcpu,omitempty"`
}
