/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DeskaasUser Desktop As A Service User
type DeskaasUser struct {
	ActivationState string `json:"activationState,omitempty"`

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`

	State string `json:"state,omitempty"`

	UserID int64 `json:"userId,omitempty"`
}
