/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Operation on a Desktop As A Service component
type DeskaasTask struct {

	// Current progress description
	Description string `json:"description,omitempty"`

	// Task last modification date
	LastModificationDate time.Time `json:"lastModificationDate,omitempty"`

	// Task name
	Name string `json:"name,omitempty"`

	// Current progress
	Progress int64 `json:"progress,omitempty"`

	// Current Task state
	State string `json:"state,omitempty"`

	// Task id
	TaskId int64 `json:"taskId,omitempty"`
}
