/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about installed package for a given image
type DistributionImage struct {

	// The image name
	Name string `json:"name,omitempty"`

	// Packages informations
	Packages []DistributionImagePackage `json:"packages,omitempty"`

	Properties DistributionImageProperties `json:"properties,omitempty"`

	// The service type name
	Service string `json:"service,omitempty"`
}
