/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Metrics about slave usage
type DockerSlaveMetrics struct {

	Resources DockerSlaveMetricsResources `json:"resources,omitempty"`

	UsedResources DockerSlaveMetricsUsedResources `json:"usedResources,omitempty"`
}
