/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DockerSLAveFrameworkAppPort Application ports
type DockerSLAveFrameworkAppPort struct {

	// ContainerPort Container port
	ContainerPort int64 `json:"containerPort,omitempty"`

	// HostPort Host port
	HostPort int64 `json:"hostPort,omitempty"`

	// Protocol Port protocol
	Protocol string `json:"protocol,omitempty"`
}
