/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DockerStack An isolated client Docker PaaS environment
type DockerStack struct {

	// Cluster The cluster on which the stack is deployed
	Cluster string `json:"cluster,omitempty"`

	// CreatedAt Date of the resource creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// LoadBalancer The DNS address of the stack load balancer
	LoadBalancer string `json:"loadBalancer,omitempty"`

	Metrics *DockerSLAveMetrics `json:"metrics,omitempty"`

	// Name The stack name
	Name string `json:"name,omitempty"`

	// SLAves A list of slave UUIDs
	SLAves []string `json:"slaves,omitempty"`

	// UpdatedAt Date of the resource last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
