/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Application data
type DockerSlaveFrameworkApp struct {

	// Application CPU
	Cpu int64 `json:"cpu,omitempty"`

	// Application environment
	Env []DockerSlaveFrameworkAppEnvironment `json:"env,omitempty"`

	// Application id
	Id string `json:"id,omitempty"`

	// Application image
	Image string `json:"image,omitempty"`

	// Application memory
	Mem int64 `json:"mem,omitempty"`

	// Application ports
	Ports []DockerSlaveFrameworkAppPort `json:"ports,omitempty"`

	// Application status
	Status string `json:"status,omitempty"`

	// Application volumes
	Volumes []DockerSlaveFrameworkAppVolume `json:"volumes,omitempty"`
}
