/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Metrics about available slave resources
type DockerSlaveMetricsResources struct {

	// Available CPU
	Cpu int64 `json:"cpu,omitempty"`

	// Available memory
	Mem int64 `json:"mem,omitempty"`
}
