/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DockerSLAveMetricsUsedResources Metrics about used slave resources
type DockerSLAveMetricsUsedResources struct {

	// CPU Used CPU
	CPU int64 `json:"cpu,omitempty"`

	// Mem Used memory
	Mem int64 `json:"mem,omitempty"`
}
