/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DockerStackCustomSSLMessage Action validation message
type DockerStackCustomSSLMessage struct {

	// Message The action validation message
	Message string `json:"message,omitempty"`
}
