/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DockerSLAveFrameworkApp Application data
type DockerSLAveFrameworkApp struct {

	// CPU Application CPU
	CPU int64 `json:"cpu,omitempty"`

	// Env Application environment
	Env []*DockerSLAveFrameworkAppEnvironment `json:"env,omitempty"`

	// ID Application id
	ID string `json:"id,omitempty"`

	// Image Application image
	Image string `json:"image,omitempty"`

	// Instances Number of running containers instances
	Instances int64 `json:"instances,omitempty"`

	// Mem Application memory
	Mem int64 `json:"mem,omitempty"`

	// Ports Application ports
	Ports []*DockerSLAveFrameworkAppPort `json:"ports,omitempty"`

	// Status Application status
	Status string `json:"status,omitempty"`

	// Volumes Application volumes
	Volumes []*DockerSLAveFrameworkAppVolume `json:"volumes,omitempty"`
}
