/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainDNSsecKey Domain's DNSSEC Key
type DomainDNSsecKey struct {

	// Algorithm Algorithm number of the DNSSEC key
	Algorithm int64 `json:"algorithm,omitempty"`

	// Flags Flag of the DNSSEC key
	Flags int64 `json:"flags,omitempty"`

	// ID Id of the DNSSEC key
	ID int64 `json:"id,omitempty"`

	// PublicKey Public key
	PublicKey string `json:"publicKey,omitempty"`

	// Status Key status of the DNSSEC key
	Status string `json:"status,omitempty"`

	// Tag Tag of the DNSSEC key
	Tag int64 `json:"tag,omitempty"`
}
