/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainZoneDynHostLogin Manage DynHost login
type DomainZoneDynHostLogin struct {

	// Login Login
	Login string `json:"login,omitempty"`

	// SubDomain Subdomain that the login will be allowed to update (* to allow all)
	SubDomain string `json:"subDomain,omitempty"`

	// Zone Zone
	Zone string `json:"zone,omitempty"`
}
