/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// CurrentNameServer
type DomainCurrentNameServer struct {

	// Host of the name server
	Host string `json:"host,omitempty"`

	// Id of the name server
	Id int64 `json:"id,omitempty"`

	// Ip of the name server
	Ip string `json:"ip,omitempty"`

	// isUsed flag of the name server
	IsUsed bool `json:"isUsed,omitempty"`

	// toDelete flag of the name server
	ToDelete bool `json:"toDelete,omitempty"`
}
