/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainGlueRecordPost ...
type DomainGlueRecordPost struct {
	Host string `json:"host,omitempty"`

	IPs []string `json:"ips,omitempty"`
}
