/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Definition of claim notices applying to a domain name
type DomainDataClaimNoticeClaimNotice struct {

	// Array of claim notice for the domain
	Claims []DomainDataClaimNoticeClaimNoticeDecision `json:"claims,omitempty"`

	// Ending date of claim notice
	EndingDate string `json:"endingDate,omitempty"`

	// Claim notice ID
	Id string `json:"id,omitempty"`

	// Label referring to claim notice
	Label string `json:"label,omitempty"`

	// Beginning date of claim notice
	StartingDate string `json:"startingDate,omitempty"`

	// Type of claim notice
	Type_ string `json:"type,omitempty"`
}
