/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainDataClaimNoticeContact Contact definition of a claim notice holder
type DomainDataClaimNoticeContact struct {
	Address *DomainDataClaimNoticeAddress `json:"address,omitempty"`

	// Email Email address
	Email string `json:"email,omitempty"`

	// Entitlement Legitimacy of holder
	Entitlement string `json:"entitlement,omitempty"`

	// Name Name of claim notice holder
	Name string `json:"name,omitempty"`

	// Organisation Organisation name
	Organisation string `json:"organisation,omitempty"`

	// TType Type of contact
	TType string `json:"type,omitempty"`
}
