/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainDataAfnicCorporationTrademarkInformationPost ...
type DomainDataAfnicCorporationTrademarkInformationPost struct {
	ContactID int64 `json:"contactId,omitempty"`

	InpiNumber string `json:"inpiNumber,omitempty"`

	InpiTrademarkOwner string `json:"inpiTrademarkOwner,omitempty"`
}
