/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Tasks associated to domain
type DomainTask struct {

	// Can accelerate the task
	CanAccelerate bool `json:"canAccelerate,omitempty"`

	// Can cancel the task
	CanCancel bool `json:"canCancel,omitempty"`

	// Can relaunch the task
	CanRelaunch bool `json:"canRelaunch,omitempty"`

	// Comment about the task
	Comment string `json:"comment,omitempty"`

	// Creation date of the task
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Done date of the task
	DoneDate time.Time `json:"doneDate,omitempty"`

	// Function of the task
	Function string `json:"function,omitempty"`

	// Id of the task
	Id int64 `json:"id,omitempty"`

	// Last update date of the task
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Status of the task
	Status string `json:"status,omitempty"`

	// Todo date of the task
	TodoDate time.Time `json:"todoDate,omitempty"`
}
