/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DynHost record
type DomainZoneDynHostRecord struct {

	// Id of the DynHost record
	Id int64 `json:"id,omitempty"`

	// Ip address of the DynHost record
	Ip string `json:"ip,omitempty"`

	// Subdomain of the DynHost record
	SubDomain string `json:"subDomain,omitempty"`

	// Zone of the DynHost record
	Zone string `json:"zone,omitempty"`
}
