/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainDataClaimNoticeClassification Definition of a trademark claim notice classification
type DomainDataClaimNoticeClassification struct {

	// Description Summary of the classification
	Description string `json:"description,omitempty"`

	// Number Code of the classification
	Number string `json:"number,omitempty"`
}
