/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// DomainNsStatus DNS server status
type DomainNsStatus struct {

	// State Whether or not the DNS server is working
	State string `json:"state,omitempty"`

	// TType Whether or not the DNS server is managed by OVH
	TType string `json:"type,omitempty"`

	// UsedSince Date from which the DNS server is used by the domain
	UsedSince *time.Time `json:"usedSince,omitempty"`
}
