/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Zone dns Management
type DomainZoneZone struct {

	// Is DNSSEC supported by this zone
	DnssecSupported bool `json:"dnssecSupported,omitempty"`

	// hasDnsAnycast flag of the DNS zone
	HasDnsAnycast bool `json:"hasDnsAnycast,omitempty"`

	// Last update date of the DNS zone
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Name servers that host the DNS zone
	NameServers []string `json:"nameServers,omitempty"`
}
