/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Representation of an Inpi additional information for a corporation
type DomainDataAfnicCorporationTrademarkContact struct {

	// Contact ID related to the Inpi additional information
	ContactId int64 `json:"contactId,omitempty"`

	// Corporation Inpi additional information ID
	Id int64 `json:"id,omitempty"`

	// Number of the Inpi declaration
	InpiNumber string `json:"inpiNumber,omitempty"`

	// Owner of the trademark
	InpiTrademarkOwner string `json:"inpiTrademarkOwner,omitempty"`
}
