/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Address for a claim notice holder
type DomainDataClaimNoticeAddress struct {

	// City
	City string `json:"city,omitempty"`

	// Country code
	CountryCode string `json:"countryCode,omitempty"`

	// Fax number
	Fax string `json:"fax,omitempty"`

	// Fax number extension
	FaxExtension string `json:"faxExtension,omitempty"`

	// Postal zip code
	PostalCode string `json:"postalCode,omitempty"`

	// State of province
	StateOrProvince string `json:"stateOrProvince,omitempty"`

	// Array of street name
	Streets []string `json:"streets,omitempty"`

	// Phone number
	Voice string `json:"voice,omitempty"`

	// Phone number extension
	VoiceExtension string `json:"voiceExtension,omitempty"`
}
