/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Domain name administration
type DomainDomain struct {

	// Is DNSSEC implemented for this domain name's tld
	DnssecSupported bool `json:"dnssecSupported,omitempty"`

	// Domain name
	Domain string `json:"domain,omitempty"`

	// Does the registry support ipv6 glue record
	GlueRecordIpv6Supported bool `json:"glueRecordIpv6Supported,omitempty"`

	// Does the registry support multi ip glue record
	GlueRecordMultiIpSupported bool `json:"glueRecordMultiIpSupported,omitempty"`

	// Last update date
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Name servers type
	NameServerType string `json:"nameServerType,omitempty"`

	// Domain's offer
	Offer string `json:"offer,omitempty"`

	// Is whois obfuscation supported by this domain name's registry
	OwoSupported bool `json:"owoSupported,omitempty"`

	ParentService DomainParentService `json:"parentService,omitempty"`

	// Transfer lock status
	TransferLockStatus string `json:"transferLockStatus,omitempty"`

	// Contact Owner (you can edit it via /me/contact/<ID>)
	WhoisOwner string `json:"whoisOwner,omitempty"`
}
