/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DomainCurrentNameServer CurrentNameServer
type DomainCurrentNameServer struct {

	// Host Host of the name server
	Host string `json:"host,omitempty"`

	// ID Id of the name server
	ID int64 `json:"id,omitempty"`

	// IP Ip of the name server
	IP string `json:"ip,omitempty"`

	// IsUsed isUsed flag of the name server
	IsUsed bool `json:"isUsed,omitempty"`

	// ToDelete toDelete flag of the name server
	ToDelete bool `json:"toDelete,omitempty"`
}
