/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Definition of a court decision
type DomainDataClaimNoticeCourtDecision struct {

	// Country code
	CountryCode string `json:"countryCode,omitempty"`

	// Court name
	CourtName string `json:"courtName,omitempty"`

	// Reference number of court decision
	ReferenceNumber string `json:"referenceNumber,omitempty"`

	// Regions where court decision apply
	Regions []string `json:"regions,omitempty"`
}
