/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// EmailExchangeSharedAccount Exchange shared mailbox
type EmailExchangeSharedAccount struct {

	// CreationDate Creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// CurrentUsage Shared mailbox usage
	CurrentUsage int64 `json:"currentUsage,omitempty"`

	// DisplayName Shared account display name
	DisplayName string `json:"displayName,omitempty"`

	// FirstName Shared account first name
	FirstName string `json:"firstName,omitempty"`

	// HiddenFromGAL Hide shared account in Global Address List
	HiddenFromGAL bool `json:"hiddenFromGAL,omitempty"`

	// ID Shared account id
	ID int64 `json:"id,omitempty"`

	// Initials Shared account initials
	Initials string `json:"initials,omitempty"`

	// LastLogoffDate Last logoff
	LastLogoffDate *time.Time `json:"lastLogoffDate,omitempty"`

	// LastLogonDate Last logon
	LastLogonDate *time.Time `json:"lastLogonDate,omitempty"`

	// LastName Shared account last name
	LastName string `json:"lastName,omitempty"`

	// MailingFilter Enable or disable anti-virus and anti-spam
	MailingFilter []string `json:"mailingFilter,omitempty"`

	// Quota Shared account maximum size
	Quota int64 `json:"quota,omitempty"`

	// SharedEmailAddress Default email for this shared mailbox
	SharedEmailAddress string `json:"sharedEmailAddress,omitempty"`

	// SpamDetected Account was sending spam
	SpamDetected bool `json:"spamDetected,omitempty"`

	// SpamTicketNumber Ticket number of spam detection
	SpamTicketNumber int64 `json:"spamTicketNumber,omitempty"`

	// State Shared account state
	State string `json:"state,omitempty"`

	// TaskPendingID Pending tasks for this shared account
	TaskPendingID int64 `json:"taskPendingId,omitempty"`
}
