/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Export PST file url
type EmailExchangeExportUrl struct {

	// Url expiration date
	Expiration time.Time `json:"expiration,omitempty"`

	// Export url
	Url string `json:"url,omitempty"`
}
