/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Get the list of your ActiveSync devices registered on this Exchange service
type EmailExchangeExchangeServiceDevice struct {

	// International Mobile Equipment Identity
	IMEI string `json:"IMEI,omitempty"`

	// Creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Device Id
	DeviceId string `json:"deviceId,omitempty"`

	// Model device
	DeviceModel string `json:"deviceModel,omitempty"`

	// Device State
	DeviceState string `json:"deviceState,omitempty"`

	// user guid
	Guid string `json:"guid,omitempty"`

	// Exchange identity
	Identity string `json:"identity,omitempty"`

	// Last update date
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Pending task id
	TaskPendingId int64 `json:"taskPendingId,omitempty"`
}
