/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type EmailExchangeServiceResourceAccountPost struct {

	AllowConflict bool `json:"allowConflict,omitempty"`

	Capacity int64 `json:"capacity,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	ResourceEmailAddress string `json:"resourceEmailAddress,omitempty"`

	Type_ string `json:"type,omitempty"`
}
