/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// EmailDomainAccountDelegated Account List
type EmailDomainAccountDelegated struct {

	// AccountName Name of account
	AccountName string `json:"accountName,omitempty"`

	// AllowedAccountSize List of allowed sizes for this account in bytes
	AllowedAccountSize []int64 `json:"allowedAccountSize,omitempty"`

	// Description Account description
	Description string `json:"description,omitempty"`

	// Domain Name of domain
	Domain string `json:"domain,omitempty"`

	// Email Email
	Email string `json:"email,omitempty"`

	// IsBlocked If true your account is blocked
	IsBlocked bool `json:"isBlocked,omitempty"`

	// Size Size of your account in bytes
	Size int64 `json:"size,omitempty"`
}
