/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// EmailExchangeServiceActiveSyncNotification Get email addresses subscribed to ActiveSync quarantine notifications
type EmailExchangeServiceActiveSyncNotification struct {

	// CreationDate Creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// NotifiedAccountID Notified Account Id
	NotifiedAccountID int64 `json:"notifiedAccountId,omitempty"`

	// PrimaryEmailAddress Primary email address for notified account
	PrimaryEmailAddress string `json:"primaryEmailAddress,omitempty"`

	// State Email state
	State string `json:"state,omitempty"`
}
