/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type EmailExchangeServicePublicFolderPost struct {

	AnonymousPermission string `json:"anonymousPermission,omitempty"`

	DefaultPermission string `json:"defaultPermission,omitempty"`

	Path string `json:"path,omitempty"`

	Quota int64 `json:"quota,omitempty"`

	Type_ string `json:"type,omitempty"`
}
