/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// EmailDomainTaskMl Task Mailing List
type EmailDomainTaskMl struct {
	Account string `json:"account,omitempty"`

	Action string `json:"action,omitempty"`

	Date *time.Time `json:"date,omitempty"`

	Domain string `json:"domain,omitempty"`

	ID int64 `json:"id,omitempty"`

	Language string `json:"language,omitempty"`
}
