/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Exchange organization disclaimer
type EmailExchangeDisclaimer struct {

	// Signature, added at the bottom of your organization emails
	Content string `json:"content,omitempty"`

	// Creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Disclaimer name
	Name string `json:"name,omitempty"`

	// Activate the disclaimer only for external emails
	OutsideOnly bool `json:"outsideOnly,omitempty"`

	// task pending id
	TaskPendingId int64 `json:"taskPendingId,omitempty"`
}
