/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Task Pop List
type EmailDomainTaskPop struct {

	// Action of task
	Action string `json:"action,omitempty"`

	// Creation date of task
	Date time.Time `json:"date,omitempty"`

	// Domain name of task
	Domain string `json:"domain,omitempty"`

	// Id of task
	Id int64 `json:"id,omitempty"`

	// Account name of task
	Name string `json:"name,omitempty"`
}
