/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Exchange resource account
type EmailExchangeResourceAccount struct {

	// resource can be scheduled by more than one person during the same time period
	AllowConflict bool `json:"allowConflict,omitempty"`

	// number of the same equipment or capacity of a room
	Capacity int64 `json:"capacity,omitempty"`

	// Creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// name of resource
	DisplayName string `json:"displayName,omitempty"`

	// resource as email
	ResourceEmailAddress string `json:"resourceEmailAddress,omitempty"`

	// account state
	State string `json:"state,omitempty"`

	// task pending id
	TaskPendingId int64 `json:"taskPendingId,omitempty"`

	// resource type
	Type_ string `json:"type,omitempty"`
}
