/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Exchange mailbox
type EmailExchangeAccount struct {

	// SAM account name
	SAMAccountName string `json:"SAMAccountName,omitempty"`

	// Exchange account type
	AccountLicense string `json:"accountLicense,omitempty"`

	// Indicates if the account is configured
	Configured bool `json:"configured,omitempty"`

	// Creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Mailbox usage
	CurrentUsage int64 `json:"currentUsage,omitempty"`

	// delete at expiration
	DeleteAtExpiration bool `json:"deleteAtExpiration,omitempty"`

	// delete outlook at expiration
	DeleteOutlookAtExpiration bool `json:"deleteOutlookAtExpiration,omitempty"`

	// Account display name
	DisplayName string `json:"displayName,omitempty"`

	// Email domain
	Domain string `json:"domain,omitempty"`

	// exchangeGuid for manual configuration
	ExchangeGuid string `json:"exchangeGuid,omitempty"`

	// expiration date
	ExpirationDate time.Time `json:"expirationDate,omitempty"`

	// expiration date
	ExpirationOutlookDate time.Time `json:"expirationOutlookDate,omitempty"`

	// Account first name
	FirstName string `json:"firstName,omitempty"`

	// GUID for user in active directory
	Guid string `json:"guid,omitempty"`

	// Hide account in Global Address List
	HiddenFromGAL bool `json:"hiddenFromGAL,omitempty"`

	// Account id
	Id int64 `json:"id,omitempty"`

	// Account initials
	Initial string `json:"initial,omitempty"`

	// Last logoff
	LastLogoffDate time.Time `json:"lastLogoffDate,omitempty"`

	// Last logon
	LastLogonDate time.Time `json:"lastLogonDate,omitempty"`

	// Account last name
	LastName string `json:"lastName,omitempty"`

	// Last update
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`

	// Account login
	Login string `json:"login,omitempty"`

	// Enable or disable anti-virus and anti-spam
	MailingFilter []string `json:"mailingFilter,omitempty"`

	// Outlook licence
	OutlookLicense bool `json:"outlookLicense,omitempty"`

	// Time of account's password last update
	PasswordLastUpdate time.Time `json:"passwordLastUpdate,omitempty"`

	// Default email for this mailbox
	PrimaryEmailAddress string `json:"primaryEmailAddress,omitempty"`

	// Account maximum size
	Quota int64 `json:"quota,omitempty"`

	// change the renew period for outlook
	RenewOutlookPeriod string `json:"renewOutlookPeriod,omitempty"`

	// change the renew period
	RenewPeriod string `json:"renewPeriod,omitempty"`

	SpamAndVirusConfiguration EmailExchangeSpamAndVirusConfiguration `json:"spamAndVirusConfiguration,omitempty"`

	// Account was sending spam
	SpamDetected bool `json:"spamDetected,omitempty"`

	// Ticket number of spam detection
	SpamTicketNumber int64 `json:"spamTicketNumber,omitempty"`

	// Account state
	State string `json:"state,omitempty"`

	// Pending tasks for this account
	TaskPendingId int64 `json:"taskPendingId,omitempty"`
}
