/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Account List
type EmailDomainAccount struct {

	// Name of account
	AccountName string `json:"accountName,omitempty"`

	// Account description
	Description string `json:"description,omitempty"`

	// Name of domain
	Domain string `json:"domain,omitempty"`

	// Email
	Email string `json:"email,omitempty"`

	// If true your account is blocked
	IsBlocked bool `json:"isBlocked,omitempty"`

	// Size of your account in bytes
	Size int64 `json:"size,omitempty"`
}
