/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// EmailExchangeResourceAccount Exchange resource account
type EmailExchangeResourceAccount struct {

	// AllowConflict resource can be scheduled by more than one person during the same time period
	AllowConflict bool `json:"allowConflict,omitempty"`

	// Capacity number of the same equipment or capacity of a room
	Capacity int64 `json:"capacity,omitempty"`

	// CreationDate Creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// DisplayName name of resource
	DisplayName string `json:"displayName,omitempty"`

	// ResourceEmailAddress resource as email
	ResourceEmailAddress string `json:"resourceEmailAddress,omitempty"`

	// State account state
	State string `json:"state,omitempty"`

	// TaskPendingID task pending id
	TaskPendingID int64 `json:"taskPendingId,omitempty"`

	// TType resource type
	TType string `json:"type,omitempty"`
}
