/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// EmailDomainAccountPost ...
type EmailDomainAccountPost struct {
	AccountName string `json:"accountName,omitempty"`

	Description string `json:"description,omitempty"`

	Password string `json:"password,omitempty"`

	Size int64 `json:"size,omitempty"`
}
