/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// EmailExchangeResourceAccountDelegate Resource accounts delegates
type EmailExchangeResourceAccountDelegate struct {

	// AllowedAccountID delegate's account id
	AllowedAccountID int64 `json:"allowedAccountId,omitempty"`

	// CreationDate Creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// DelegateEmailAddress Delegate account primaryEmailAddress
	DelegateEmailAddress string `json:"delegateEmailAddress,omitempty"`

	// TaskPendingID task pending id
	TaskPendingID int64 `json:"taskPendingId,omitempty"`
}
