/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type EmailDomainAccountFilterRulePost struct {

	Header string `json:"header,omitempty"`

	Operand string `json:"operand,omitempty"`

	Value string `json:"value,omitempty"`
}
