/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// All informations about access point
type HorizonViewPool struct {

	// Pool id
	AccessPointId int64 `json:"accessPointId,omitempty"`

	// DHCP netmask in this port group
	DhcpNetmask string `json:"dhcpNetmask,omitempty"`

	// DHCP network in this port group
	DhcpNetwork string `json:"dhcpNetwork,omitempty"`

	// External url of your access point
	ExternalUrl string `json:"externalUrl,omitempty"`

	// Port group id
	PortGroupId string `json:"portGroupId,omitempty"`

	// Network state
	State string `json:"state,omitempty"`
}
