/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingPrivateDatabaseGraphEndpoint Parameters required to query metrics from OpenTSDB
type HostingPrivateDatabaseGraphEndpoint struct {

	// Host The OpenTSDB host
	Host string `json:"host,omitempty"`

	// ReadToken A read-only token
	ReadToken string `json:"readToken,omitempty"`

	// ReadTokenID A read-only token ID
	ReadTokenID string `json:"readTokenId,omitempty"`
}
