/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Tasks
type HostingPrivateDatabaseTask struct {

	// Database name on which the task is working
	DatabaseName string `json:"databaseName,omitempty"`

	// Completion date
	DoneDate time.Time `json:"doneDate,omitempty"`

	// DumpId on which the task is working
	DumpId int64 `json:"dumpId,omitempty"`

	// Function name
	Function string `json:"function,omitempty"`

	// The id of the task
	Id int64 `json:"id,omitempty"`

	// Last update
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Task Creation date
	StartDate time.Time `json:"startDate,omitempty"`

	// Task status
	Status string `json:"status,omitempty"`

	// User name on which the task is working
	UserName string `json:"userName,omitempty"`
}
