/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// HostingPrivateDatabaseService Private database
type HostingPrivateDatabaseService struct {

	// CPU Number of cpu on your private database
	CPU int64 `json:"cpu,omitempty"`

	// Datacenter Datacenter where this private database is located
	Datacenter string `json:"datacenter,omitempty"`

	// DisplayName Set the name displayed in customer panel for your private database (max 50 chars)
	DisplayName string `json:"displayName,omitempty"`

	GraphEndpoint *HostingPrivateDatabaseGraphEndpoint `json:"graphEndpoint,omitempty"`

	// GuiURL URL for the graphical user interface
	GuiURL string `json:"guiURL,omitempty"`

	// Hostname Private database hostname
	Hostname string `json:"hostname,omitempty"`

	// HostnameFtp Private database ftp hostname
	HostnameFtp string `json:"hostnameFtp,omitempty"`

	// Infrastructure Infrastructure where service was stored
	Infrastructure string `json:"infrastructure,omitempty"`

	// IP Private database ip
	IP string `json:"ip,omitempty"`

	// LastCheck Date of the last data synchronization
	LastCheck *time.Time `json:"lastCheck,omitempty"`

	// Port Private database service port
	Port int64 `json:"port,omitempty"`

	// PortFtp Private database ftp port
	PortFtp int64 `json:"portFtp,omitempty"`

	QuotaSize *HostingPrivateDatabaseServiceQuotaSize `json:"quotaSize,omitempty"`

	QuotaUsed *HostingPrivateDatabaseServiceQuotaUsed `json:"quotaUsed,omitempty"`

	RAM *HostingPrivateDatabaseServiceRAM `json:"ram,omitempty"`

	// Server Private database server name
	Server string `json:"server,omitempty"`

	// ServiceName Service name
	ServiceName string `json:"serviceName,omitempty"`

	// State Private database state
	State string `json:"state,omitempty"`

	// TType Private database type
	TType string `json:"type,omitempty"`

	// Version Private database version
	Version string `json:"version,omitempty"`
}
