/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWindowsService Windows web Hosting
type HostingWindowsService struct {

	// Offer Hosting offer
	Offer string `json:"offer,omitempty"`

	// OperatingSystem Hosting's OS
	OperatingSystem string `json:"operatingSystem,omitempty"`

	// ResourceType Hosting resource type
	ResourceType string `json:"resourceType,omitempty"`

	// ServiceName Service name
	ServiceName string `json:"serviceName,omitempty"`
}
