/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebCreationEmailCapabilities Struct which describes mail offer available and his quota
type HostingWebCreationEmailCapabilities struct {

	// Available Number of email available for creation
	Available int64 `json:"available,omitempty"`

	Quota *HostingWebCreationEmailCapabilitiesQuota `json:"quota,omitempty"`
}
