/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingResellerProduct Reseller
type HostingResellerProduct struct {

	// Action Current action done on the instance
	Action string `json:"action,omitempty"`

	// IP Ip address of the Plesk instance
	IP string `json:"ip,omitempty"`

	// Progress Progression of an action on the instance if any
	Progress float64 `json:"progress,omitempty"`

	// Status Status of the instance
	Status string `json:"status,omitempty"`

	// TType Reseller flavor
	TType string `json:"type,omitempty"`

	TypeDetail *HostingResellerProductType `json:"typeDetail,omitempty"`

	// URL Plesk server address
	URL string `json:"url,omitempty"`
}
