/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// HostingWebMailBounce The volume history type
type HostingWebMailBounce struct {

	// Date The datetime of this bounce
	Date *time.Time `json:"date,omitempty"`

	// Message The return message for this bounce
	Message string `json:"message,omitempty"`

	// To The email where you have the bounce
	To string `json:"to,omitempty"`
}
