/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Freedoms linked to this hosting account
type HostingWebFreedom struct {

	// Freedom domain
	Domain string `json:"domain,omitempty"`

	// Available status for freedom
	Status string `json:"status,omitempty"`

	// Freedom type
	Type_ string `json:"type,omitempty"`
}
