/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type HostingWebOvhConfigChangeConfigurationPost struct {

	Container string `json:"container,omitempty"`

	EngineName string `json:"engineName,omitempty"`

	EngineVersion string `json:"engineVersion,omitempty"`

	Environment string `json:"environment,omitempty"`

	HttpFirewall string `json:"httpFirewall,omitempty"`
}
