/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Struct which describs an boost offer from a service
type HostingWebAvailableOfferStruct struct {

	// Available boost offer
	Offer string `json:"offer,omitempty"`

	Price OrderPrice `json:"price,omitempty"`
}
