/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Struct which describs an offer
type HostingWebCapabilities struct {

	// Number of domains you can attach to your hosting
	AttachedDomains int64 `json:"attachedDomains,omitempty"`

	// Tell if you have acces to crontab
	Crontab bool `json:"crontab,omitempty"`

	// Describe all databases type you can have
	Databases []HostingWebDatabaseCreationDatabaseCapabilities `json:"databases,omitempty"`

	Disk HostingWebCapabilitiesDisk `json:"disk,omitempty"`

	Emails HostingWebCreationEmailCapabilities `json:"emails,omitempty"`

	// Number of ftp user you can create
	ExtraUsers int64 `json:"extraUsers,omitempty"`

	// Tell if you have acces to module on click
	ModuleOneClick bool `json:"moduleOneClick,omitempty"`

	// Describe all privateDatabases type you can have
	PrivateDatabases []HostingWebDatabaseCreationDatabaseCapabilities `json:"privateDatabases,omitempty"`

	// Number of sites recommended for your hosting ( -1 for unlimited )
	SitesRecommended int64 `json:"sitesRecommended,omitempty"`

	// Tell if you have acces to ssh
	Ssh bool `json:"ssh,omitempty"`

	Traffic HostingWebCapabilitiesTraffic `json:"traffic,omitempty"`
}
