/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebDatabaseAvailableVersionStruct Database Available and Default version
type HostingWebDatabaseAvailableVersionStruct struct {

	// TDefault Database default version
	TDefault string `json:"default,omitempty"`

	// List Database available version
	List []string `json:"list,omitempty"`
}
