/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebModuleListLanguageRequirement Minimal language version required to run this module
type HostingWebModuleListLanguageRequirement struct {
	Unit string `json:"unit,omitempty"`

	Value string `json:"value,omitempty"`
}
