/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// HostingWebMailVolumeHistory The volume history type
type HostingWebMailVolumeHistory struct {

	// Date The datetime of this volume history point
	Date *time.Time `json:"date,omitempty"`

	// Volume The volume history size
	Volume int64 `json:"volume,omitempty"`
}
