/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebAttachedDomain Virtual service
type HostingWebAttachedDomain struct {

	// CDN Is linked to the hosting cdn
	CDN string `json:"cdn,omitempty"`

	// Domain Domain linked (fqdn)
	Domain string `json:"domain,omitempty"`

	// Firewall Firewall state for this path
	Firewall string `json:"firewall,omitempty"`

	// IPLocation IP location of the domain linked
	IPLocation string `json:"ipLocation,omitempty"`

	// OwnLog Put domain for separate the logs
	OwnLog string `json:"ownLog,omitempty"`

	// Path Domain path, relative to your home directory
	Path string `json:"path,omitempty"`

	// SSL Put domain in ssl certificate
	SSL bool `json:"ssl,omitempty"`
}
