/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebIndy Hosting indys
type HostingWebIndy struct {

	// AttachedDomains AttachedDomain IDs linked to this multidomain
	AttachedDomains []string `json:"attachedDomains,omitempty"`

	// Home Home directory
	Home string `json:"home,omitempty"`

	// Login Login of the multidomain independent user
	Login string `json:"login,omitempty"`

	// State User status
	State string `json:"state,omitempty"`
}
