/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// HostingWebExtrasqlperso Sqlperso service
type HostingWebExtrasqlperso struct {

	// Database Number of database allowed by this option
	Database int64 `json:"database,omitempty"`

	// Name The extraSqlPerso option name
	Name string `json:"name,omitempty"`

	Size *HostingWebExtrasqlpersoSize `json:"size,omitempty"`

	// Status The extraSqlPerso option status
	Status string `json:"status,omitempty"`
}
