/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// HostingPrivateDatabaseDatabase Databases
type HostingPrivateDatabaseDatabase struct {

	// BackupTime Time of the next backup ( every day )
	BackupTime string `json:"backupTime,omitempty"`

	// CreationDate Creation date of the database
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// DatabaseName Database name
	DatabaseName string `json:"databaseName,omitempty"`

	QuotaUsed *HostingPrivateDatabaseDatabaseQuotaUsed `json:"quotaUsed,omitempty"`

	// Users Users granted to this database
	Users []*HostingPrivateDatabaseDatabaseUser `json:"users,omitempty"`
}
