/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type HostingWebAttachedDomainPost struct {

	Cdn string `json:"cdn,omitempty"`

	Domain string `json:"domain,omitempty"`

	Firewall string `json:"firewall,omitempty"`

	OwnLog string `json:"ownLog,omitempty"`

	Path string `json:"path,omitempty"`

	Ssl bool `json:"ssl,omitempty"`
}
