/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Detail of a HPC Spot consumtion
type HpcspotConsumption struct {

	// Description of the ressource
	Description string `json:"description,omitempty"`

	// Date of the completion of the item consumption
	HpcspotItemEndDate time.Time `json:"hpcspotItemEndDate,omitempty"`

	// ID of the linked job on HPC Spot interface
	HpcspotItemId int64 `json:"hpcspotItemId,omitempty"`

	// URL for the description of the consumption on the HPC Spot interface
	HpcspotUrl string `json:"hpcspotUrl,omitempty"`

	// ID of the detail
	Id int64 `json:"id,omitempty"`

	// ID of the Order that billed this item. If null, this item has not been billed
	OrderId int64 `json:"orderId,omitempty"`

	Quantity HpcspotConsumptionQuantity `json:"quantity,omitempty"`

	// Reference of the item. This reference is linked with the type of the item
	Reference string `json:"reference,omitempty"`

	// Type of consumption
	Type_ string `json:"type,omitempty"`
}
