/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Task of ImapCopy
type ImapcopyTask struct {

	// Finished date of task
	FinishDate time.Time `json:"finishDate,omitempty"`

	// Id of task
	Id int64 `json:"id,omitempty"`

	// Last update of task
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// Return message of task
	Return_ string `json:"return,omitempty"`

	// Status of task
	Status string `json:"status,omitempty"`

	// Creation date of task
	TodoDate time.Time `json:"todoDate,omitempty"`
}
