/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// IPBlockedIP Blocked IP information
type IPBlockedIP struct {

	// BlockedSince The last blocking date
	BlockedSince *time.Time `json:"blockedSince,omitempty"`

	// IPBlocked your IP
	IPBlocked string `json:"ipBlocked,omitempty"`

	// Logs Logs
	Logs string `json:"logs,omitempty"`

	// State this IP address state
	State string `json:"state,omitempty"`

	// Time Time (in seconds) remaining before you can request your IP to be unblocked
	Time int64 `json:"time,omitempty"`
}
