/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure given all services allowed as a destination for this ip
type IpDestinations struct {

	// list of public cloud projects
	CloudProject []IpDestination `json:"cloudProject,omitempty"`

	// list of dedicated clouds
	DedicatedCloud []IpDestination `json:"dedicatedCloud,omitempty"`

	// list of dedicated servers
	DedicatedServer []IpDestination `json:"dedicatedServer,omitempty"`

	// list of load balancing services
	Iplb []IpDestination `json:"iplb,omitempty"`

	// list of vps
	Vps []IpDestination `json:"vps,omitempty"`
}
