/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Possible option for TCP
type IpFirewallOptionTcp struct {

	// TCP fragments
	Fragments bool `json:"fragments,omitempty"`

	// TCP option
	Option string `json:"option,omitempty"`
}
