/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Your IP on firewall
type IpFirewallIp struct {

	Enabled bool `json:"enabled,omitempty"`

	IpOnFirewall string `json:"ipOnFirewall,omitempty"`

	// Current state of your ip on firewall
	State string `json:"state,omitempty"`
}
