/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Rule on ip:ports
type IpGameMitigationRule struct {

	// ID of the rule
	Id int64 `json:"id,omitempty"`

	Ports IpGameMitigationRulePorts `json:"ports,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	// Current state of your rule
	State string `json:"state,omitempty"`
}
