/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// IP Your IP
type IP struct {
	CanBeTerminated bool `json:"canBeTerminated,omitempty"`

	Country string `json:"country,omitempty"`

	// Description Custom description on your ip
	Description string `json:"description,omitempty"`

	IP string `json:"ip,omitempty"`

	// OrganisationID IP block organisation Id
	OrganisationID string `json:"organisationId,omitempty"`

	RoutedTo *IPRoutedTo `json:"routedTo,omitempty"`

	TType string `json:"type,omitempty"`
}
