/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// List of tasks associated with your IP load balancing
type IpLoadBalancingTask struct {

	// The action made
	Action string `json:"action,omitempty"`

	// Creation date of your task
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Identifier of your task
	Id int64 `json:"id,omitempty"`

	// Current status of your task
	Status string `json:"status,omitempty"`
}
