/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Traffic statistics in and out on a mitigated ip
type IpMitigationStats struct {

	In IpMitigationTraffic `json:"in,omitempty"`

	Out IpMitigationTraffic `json:"out,omitempty"`

	// Traffic timestamp
	Timestamp int64 `json:"timestamp,omitempty"`
}
