/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// IPMitigationStats Traffic statistics in and out on a mitigated ip
type IPMitigationStats struct {
	In *IPMitigationTraffic `json:"in,omitempty"`

	Out *IPMitigationTraffic `json:"out,omitempty"`

	// Timestamp Traffic timestamp
	Timestamp int64 `json:"timestamp,omitempty"`
}
