/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// IPMitigationTraffic Traffic on mitigation
type IPMitigationTraffic struct {

	// Bps Bits per second
	Bps int64 `json:"bps,omitempty"`

	// Pps Paquets per second
	Pps int64 `json:"pps,omitempty"`
}
