/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about routing
type IpRoutedTo struct {

	// Service where ip is routed to
	ServiceName string `json:"serviceName,omitempty"`
}
