/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Your reverse records on IP
type IpReverseIp struct {

	IpReverse string `json:"ipReverse,omitempty"`

	Reverse string `json:"reverse,omitempty"`
}
