/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Your IP linked to service
type IpServiceIp struct {

	CanBeTerminated bool `json:"canBeTerminated,omitempty"`

	Country string `json:"country,omitempty"`

	// Custom description on your ip
	Description string `json:"description,omitempty"`

	Ip string `json:"ip,omitempty"`

	// IP block organisation Id
	OrganisationId string `json:"organisationId,omitempty"`

	RoutedTo IpRoutedTo `json:"routedTo,omitempty"`

	Type_ string `json:"type,omitempty"`
}
