/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Your IP load balancing
type IplbIp struct {

	// Set the name displayed in ManagerV6 for your iplb (max 50 chars)
	DisplayName string `json:"displayName,omitempty"`

	// Your IP load balancing
	Iplb string `json:"iplb,omitempty"`

	// The internal name of your IP load balancing
	ServiceName string `json:"serviceName,omitempty"`

	// Modern oldest compatible clients : Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and Java 8. Intermediate oldest compatible clients : Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7. Intermediate if null.
	SslConfiguration string `json:"sslConfiguration,omitempty"`

	// Current state of your IP
	State string `json:"state,omitempty"`

	// Location where your service is
	Zone []string `json:"zone,omitempty"`
}
