/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// A structure describing the current state of an IPLB instances
type IplbInstancesState struct {

	// Internal ID of this IPLB instance
	InternalId int64 `json:"internalId,omitempty"`

	// Last update date
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`

	// Current state of this IPLB instance
	State string `json:"state,omitempty"`

	// zone of this IPLB instance
	Zone string `json:"zone,omitempty"`
}
