/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// IPLBCustomerServer Server
type IPLBCustomerServer struct {

	// Address Address of your server
	Address string `json:"address,omitempty"`

	// ID Id of your server
	ID int64 `json:"id,omitempty"`

	// Status Status attached to your server
	Status string `json:"status,omitempty"`

	// TType Type of your server
	TType string `json:"type,omitempty"`

	// Zone Zone of your server
	Zone string `json:"zone,omitempty"`
}
