/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Zone
type IplbIpZone struct {

	// Name of your zone
	Name string `json:"name,omitempty"`

	// State of your zone
	State string `json:"state,omitempty"`
}
