/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Office tenant
type LicenseOfficeOfficeTenant struct {

	// Contact's address line
	Address string `json:"address,omitempty"`

	// Contact's city
	City string `json:"city,omitempty"`

	// Tenant's display name
	DisplayName string `json:"displayName,omitempty"`

	// Contact's fisrt name
	FirstName string `json:"firstName,omitempty"`

	// Contact's fisrt name
	LastName string `json:"lastName,omitempty"`

	// Primary phone number
	Phone string `json:"phone,omitempty"`

	Status string `json:"status,omitempty"`

	// Contact's zip code
	ZipCode string `json:"zipCode,omitempty"`
}
