/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Office user
type LicenseOfficeOfficeUser struct {

	// Email used to activate Microsoft Office
	ActivationEmail string `json:"activationEmail,omitempty"`

	// User's first name
	FirstName string `json:"firstName,omitempty"`

	// User's last name
	LastName string `json:"lastName,omitempty"`

	// Licenses attributed to the user
	Licences []string `json:"licences,omitempty"`

	// User state
	Status string `json:"status,omitempty"`

	// Pending task id
	TaskPendingId int64 `json:"taskPendingId,omitempty"`
}
