/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// LicenseOfficeUserChangePasswordPost ...
type LicenseOfficeUserChangePasswordPost struct {
	NotifyEmail string `json:"notifyEmail,omitempty"`

	Password string `json:"password,omitempty"`

	ShouldSendMail bool `json:"shouldSendMail,omitempty"`
}
