/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// LicenseOrderableWindowsCompatibilityInfos All SQL options available for Windows products
type LicenseOrderableWindowsCompatibilityInfos struct {
	CompliantSQL []string `json:"compliantSql,omitempty"`

	Version string `json:"version,omitempty"`
}
