/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Your License options
type LicenseOption struct {

	// Quantity or corresponding label of the designated option enabled on your license
	Amount string `json:"amount,omitempty"`

	// Specifies whether this option can be released or not
	CanBeDeleted bool `json:"canBeDeleted,omitempty"`

	// This option expiration date
	ExpirationDate time.Time `json:"expirationDate,omitempty"`

	// This option designation
	Label string `json:"label,omitempty"`

	// This option related version
	Version string `json:"version,omitempty"`
}
