/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// MeInstallationTemplatePartitionSchemePartitionPost ...
type MeInstallationTemplatePartitionSchemePartitionPost struct {
	Filesystem string `json:"filesystem,omitempty"`

	Mountpoint string `json:"mountpoint,omitempty"`

	Raid int64 `json:"raid,omitempty"`

	Size int64 `json:"size,omitempty"`

	Step int64 `json:"step,omitempty"`

	TType string `json:"type,omitempty"`

	VolumeName string `json:"volumeName,omitempty"`
}
