/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// MePasswordRecoverPost ...
type MePasswordRecoverPost struct {
	OvhCompany string `json:"ovhCompany,omitempty"`

	OvhID string `json:"ovhId,omitempty"`
}
