/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// MonitoringConfig A list of resource configuration sets
type MonitoringConfig struct {

	// Config The configuration attributes of the resource
	Config []*MonitoringConfigPair `json:"config,omitempty"`
}
