/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// MonitoringResource Shinken resource (e.g. Host, Service, Contact, etc)
type MonitoringResource struct {

	// Config Configuration
	Config []*MonitoringConfigPair `json:"config,omitempty"`

	// CreatedAt Date of the resource creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ID Unique UUID of the resource
	ID string `json:"id,omitempty"`

	// UpdatedAt Date of the resource last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
