/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Sharepoint service
type MsServicesSharepointService struct {

	// Shared space usage in byte
	CurrentUsage int64 `json:"currentUsage,omitempty"`

	// Internal service name
	Domain string `json:"domain,omitempty"`

	// Shared space maximum size in byte
	Quota int64 `json:"quota,omitempty"`

	// Sharepoint service state
	State string `json:"state,omitempty"`

	// Task pending id
	TaskPendingId int64 `json:"taskPendingId,omitempty"`

	// Sharepoint url
	Url string `json:"url,omitempty"`
}
