/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// MsServicesSharepointService Sharepoint service
type MsServicesSharepointService struct {

	// CurrentUsage Shared space usage in byte
	CurrentUsage int64 `json:"currentUsage,omitempty"`

	// Domain Internal service name
	Domain string `json:"domain,omitempty"`

	// Quota Shared space maximum size in byte
	Quota int64 `json:"quota,omitempty"`

	// State Sharepoint service state
	State string `json:"state,omitempty"`

	// TaskPendingID Task pending id
	TaskPendingID int64 `json:"taskPendingId,omitempty"`

	// URL Sharepoint url
	URL string `json:"url,omitempty"`
}
