/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// MsServicesUpnSuffix Active Directory UPN Suffix
type MsServicesUpnSuffix struct {

	// CnameToCheck Cname record used for UPN suffix verification
	CnameToCheck string `json:"cnameToCheck,omitempty"`

	// OwnershipValidated Ownership for upn suffix confirmed
	OwnershipValidated bool `json:"ownershipValidated,omitempty"`

	// State UPN suffix state
	State string `json:"state,omitempty"`

	// Suffix UPN suffix
	Suffix string `json:"suffix,omitempty"`

	// TaskPendingID Pending task for this upnSuffix
	TaskPendingID int64 `json:"taskPendingId,omitempty"`
}
