/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Sharepoint task details
type MsServicesSharepointTask struct {

	// Completion date
	FinishDate time.Time `json:"finishDate,omitempty"`

	// Function name
	Function string `json:"function,omitempty"`

	// Task id
	Id int64 `json:"id,omitempty"`

	// Task status
	Status string `json:"status,omitempty"`

	// Creation date
	TodoDate time.Time `json:"todoDate,omitempty"`
}
