/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// NewAccountPost ...
type NewAccountPost struct {
	Address string `json:"address,omitempty"`

	Area string `json:"area,omitempty"`

	BirthCity string `json:"birthCity,omitempty"`

	BirthDay string `json:"birthDay,omitempty"`

	City string `json:"city,omitempty"`

	CompanyNationalIDentificationNumber string `json:"companyNationalIdentificationNumber,omitempty"`

	CorporationType string `json:"corporationType,omitempty"`

	Country string `json:"country,omitempty"`

	Email string `json:"email,omitempty"`

	Fax string `json:"fax,omitempty"`

	Firstname string `json:"firstname,omitempty"`

	Language string `json:"language,omitempty"`

	Legalform string `json:"legalform,omitempty"`

	Name string `json:"name,omitempty"`

	NationalIDentificationNumber string `json:"nationalIdentificationNumber,omitempty"`

	Organisation string `json:"organisation,omitempty"`

	OvhCompany string `json:"ovhCompany,omitempty"`

	OvhSubsidiary string `json:"ovhSubsidiary,omitempty"`

	Phone string `json:"phone,omitempty"`

	Sex string `json:"sex,omitempty"`

	SpareEmail string `json:"spareEmail,omitempty"`

	Vat string `json:"vat,omitempty"`

	Zip string `json:"zip,omitempty"`
}
