/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// NichandleEmailNotification Email notification
type NichandleEmailNotification struct {

	// Body This email body
	Body string `json:"body,omitempty"`

	// Date This email date
	Date *time.Time `json:"date,omitempty"`

	// ID This email Id
	ID int64 `json:"id,omitempty"`

	// Subject This email subject
	Subject string `json:"subject,omitempty"`
}
