/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Auto renewal information
type NichandleNicAutorenewInfos struct {

	// Renewal active or not
	Active bool `json:"active,omitempty"`

	// give the last renew
	LastRenew time.Time `json:"lastRenew,omitempty"`

	// give the renewal day
	RenewDay int64 `json:"renewDay,omitempty"`
}
