/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// NichandleSSHKey Customer public SSH key, can be used for rescue netboot or server access after reinstallation
type NichandleSSHKey struct {

	// TDefault True when this public SSH key is used for rescue mode and reinstallations
	TDefault bool `json:"default,omitempty"`

	// Key ASCII encoded public SSH key
	Key string `json:"key,omitempty"`

	// KeyName Name of this public SSH key
	KeyName string `json:"keyName,omitempty"`
}
