/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// NichandleEmailChangeTask Task running an email change on an account
type NichandleEmailChangeTask struct {

	// DateDone End date of that request
	DateDone *time.Time `json:"dateDone,omitempty"`

	// DateRequest Creation date of that request
	DateRequest *time.Time `json:"dateRequest,omitempty"`

	ID int64 `json:"id,omitempty"`

	// NewEmail The email address to change for
	NewEmail string `json:"newEmail,omitempty"`

	// State Current state of the request
	State string `json:"state,omitempty"`
}
