/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Describe all services impacted by SLA
type NichandleSlaService struct {

	// Service description
	Description string `json:"description,omitempty"`

	// Impacted service name
	ServiceName string `json:"serviceName,omitempty"`

	// SLA plan application
	SlaApplication string `json:"slaApplication,omitempty"`

	// SLA plan description
	SlaPlan string `json:"slaPlan,omitempty"`
}
