/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// List of all OVH things you can subscribe to
type NichandleSubscription struct {

	// Determine whether you are registered or not
	Registered bool `json:"registered,omitempty"`

	// The type of subscription
	Type_ string `json:"type,omitempty"`
}
