/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// List of all IP Restrictions
type NichandleIpRestriction struct {

	// The Id of the restriction
	Id int64 `json:"id,omitempty"`

	// An IP range where we will apply the rule
	Ip string `json:"ip,omitempty"`

	// Accept or deny IP access
	Rule string `json:"rule,omitempty"`

	// Send an email if someone try to access with this IP address
	Warning bool `json:"warning,omitempty"`
}
