/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// NichandleIPRestrictionDefaultRule IP Restriction default rule
type NichandleIPRestrictionDefaultRule struct {

	// Rule Accept or deny access
	Rule string `json:"rule,omitempty"`

	// Warning Send an email if someone try to access
	Warning bool `json:"warning,omitempty"`
}
