/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type OrderLicenseOfficeNewPost struct {

	GiftCode string `json:"giftCode,omitempty"`

	OfficeBusinessQuantity int64 `json:"officeBusinessQuantity,omitempty"`

	OfficeProPlusQuantity int64 `json:"officeProPlusQuantity,omitempty"`
}
