/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCartDomainPacksDescriptionItem Describe the eligibility of each domain in the packs
type OrderCartDomainPacksDescriptionItem struct {

	// Available Indicates if domain is available and will be included in the pack
	Available bool `json:"available,omitempty"`

	// Domain Domain concerned by the availability
	Domain string `json:"domain,omitempty"`
}
