/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Describes a Catalog
type OrderCatalogCatalog struct {

	// Identifier of the catalog
	CatalogId int64 `json:"catalogId,omitempty"`

	// OVH Subsidiary concerned by this catalog
	MerchantCode string `json:"merchantCode,omitempty"`

	// List of plans of the catalog
	PlansFamily []OrderCatalogPlansItem `json:"plansFamily,omitempty"`
}
