/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderPrices Prices of an order
type OrderPrices struct {
	Tax *OrderPrice `json:"tax,omitempty"`

	WithTax *OrderPrice `json:"withTax,omitempty"`

	WithoutTax *OrderPrice `json:"withoutTax,omitempty"`
}
