/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type OrderTelephonyAccessoryPost struct {

	Accessory string `json:"accessory,omitempty"`

	MondialRelayId int64 `json:"mondialRelayId,omitempty"`

	Quantity int64 `json:"quantity,omitempty"`

	Retractation bool `json:"retractation,omitempty"`

	ShippingContactId int64 `json:"shippingContactId,omitempty"`
}
