/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCartGenericProductDefinition Representation of a generic product
type OrderCartGenericProductDefinition struct {

	// PlanCode Product offer identifier
	PlanCode string `json:"planCode,omitempty"`

	// Prices Prices of the product offer
	Prices []*OrderCartGenericProductPricing `json:"prices,omitempty"`

	// ProductName Name of the product
	ProductName string `json:"productName,omitempty"`

	// ProductType Product type
	ProductType string `json:"productType,omitempty"`
}
