/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Order An order
type Order struct {
	Contracts []*OrderContract `json:"contracts,omitempty"`

	Details []*OrderDetail `json:"details,omitempty"`

	OrderID int64 `json:"orderId,omitempty"`

	Prices *OrderPrices `json:"prices,omitempty"`

	URL string `json:"url,omitempty"`
}
