/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCatalogProductPlan Describes of commercial offer of a product
type OrderCatalogProductPlan struct {

	// AddonsFamily List of addons
	AddonsFamily []*OrderCatalogAddonItem `json:"addonsFamily,omitempty"`

	// ConsumptionBillingStrategy Strategy that follow the pricing when product is in consumption mode
	ConsumptionBillingStrategy string `json:"consumptionBillingStrategy,omitempty"`

	Details *OrderCatalogProductOfferDetails `json:"details,omitempty"`

	// InvoiceName Name that appears on invoice
	InvoiceName string `json:"invoiceName,omitempty"`

	// PlanCode Plan code identifier
	PlanCode string `json:"planCode,omitempty"`

	// PricingType Main mode: rental, consumption
	PricingType string `json:"pricingType,omitempty"`
}
