/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about a Web Hosting offer information
type OrderCartWebHostingProductInformation struct {

	Description HostingWebCapabilities `json:"description,omitempty"`

	// Identifier of the offer
	PlanCode string `json:"planCode,omitempty"`

	// Prices of the offer
	Prices []OrderCartGenericProductPricing `json:"prices,omitempty"`
}
