/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderTelephonySpareNewPost ...
type OrderTelephonySpareNewPost struct {
	Brand string `json:"brand,omitempty"`

	MondialRelayID string `json:"mondialRelayId,omitempty"`

	Quantity int64 `json:"quantity,omitempty"`

	ShippingContactID int64 `json:"shippingContactId,omitempty"`
}
