/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCartProductInformation Information about a product for Order/Cart
type OrderCartProductInformation struct {

	// Configurations Informations about the configurations required
	Configurations []*OrderCartConfigurationRequirements `json:"configurations,omitempty"`

	// DeliveryTime Informations about the estimated delivery time for the product
	DeliveryTime string `json:"deliveryTime,omitempty"`

	// Duration List all the duration allowed for the product
	Duration []string `json:"duration,omitempty"`

	// Orderable Indicates if the product is orderable or not
	Orderable bool `json:"orderable,omitempty"`

	// Phase Informations about the domain phase
	Phase string `json:"phase,omitempty"`

	Prices *OrderCartPrice `json:"prices,omitempty"`

	// ProductID Product identifier
	ProductID string `json:"productId,omitempty"`

	// QuantityMax Maximum quantity purchasable for this product
	QuantityMax int64 `json:"quantityMax,omitempty"`
}
