/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type OrderTelephonyLinesHardwarePost struct {

	Hardware string `json:"hardware,omitempty"`

	MondialRelayId string `json:"mondialRelayId,omitempty"`

	Retractation bool `json:"retractation,omitempty"`

	ShippingContactId string `json:"shippingContactId,omitempty"`
}
