/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCartConfigurationItem Representation of a configuration item for personalizing product
type OrderCartConfigurationItem struct {

	// ID Configuration ID
	ID int64 `json:"id,omitempty"`

	// Label Identifier of the resource
	Label string `json:"label,omitempty"`

	// Value Path to the resource in API.OVH.COM
	Value string `json:"value,omitempty"`
}
