/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Representation of a generic product option
type OrderCartGenericOptionDefinition struct {

	// Define if options of this family are exclusive with each other
	Exclusive bool `json:"exclusive,omitempty"`

	// Option family
	Family string `json:"family,omitempty"`

	// Define if an option of this family is mandatory
	Mandatory bool `json:"mandatory,omitempty"`

	// Product offer identifier
	PlanCode string `json:"planCode,omitempty"`

	// Prices of the product offer
	Prices []OrderCartGenericProductPricing `json:"prices,omitempty"`

	// Name of the product
	ProductName string `json:"productName,omitempty"`

	// Product type
	ProductType string `json:"productType,omitempty"`
}
