/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderLicenseVirtuozzoNewPost ...
type OrderLicenseVirtuozzoNewPost struct {
	ContainerNumber string `json:"containerNumber,omitempty"`

	IP string `json:"ip,omitempty"`

	ServiceType string `json:"serviceType,omitempty"`

	Version string `json:"version,omitempty"`
}
