/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about a product for Order/Cart
type OrderCartProductInformation struct {

	// Informations about the configurations required
	Configurations []OrderCartConfigurationRequirements `json:"configurations,omitempty"`

	// Informations about the estimated delivery time for the product
	DeliveryTime string `json:"deliveryTime,omitempty"`

	// List all the duration allowed for the product
	Duration []string `json:"duration,omitempty"`

	// Indicates if the product is orderable or not
	Orderable bool `json:"orderable,omitempty"`

	// Informations about the domain phase
	Phase string `json:"phase,omitempty"`

	Prices OrderCartPrice `json:"prices,omitempty"`

	// Product identifier
	ProductId string `json:"productId,omitempty"`

	// Maximum quantity purchasable for this product
	QuantityMax int64 `json:"quantityMax,omitempty"`
}
