/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderCatalog Describes a Catalog
type OrderCatalog struct {

	// CatalogID Identifier of the catalog
	CatalogID int64 `json:"catalogId,omitempty"`

	// MerchantCode OVH Subsidiary concerned by this catalog
	MerchantCode string `json:"merchantCode,omitempty"`

	// PlansFamily List of plans of the catalog
	PlansFamily []*OrderCatalogPlansItem `json:"plansFamily,omitempty"`
}
