/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OrderEmailExchangeServiceAccountUpgradePost ...
type OrderEmailExchangeServiceAccountUpgradePost struct {
	NewQuota int64 `json:"newQuota,omitempty"`

	PrimaryEmailAddress string `json:"primaryEmailAddress,omitempty"`
}
