/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OverTheBoxDeviceAction Device action
type OverTheBoxDeviceAction struct {

	// ActionID The id of the action
	ActionID string `json:"actionId,omitempty"`

	// Name The name of the action
	Name string `json:"name,omitempty"`

	// Status The status of the action
	Status string `json:"status,omitempty"`
}
