/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OverTheBoxTask Task
type OverTheBoxTask struct {

	// Name The name of the task
	Name string `json:"name,omitempty"`

	// Status The status of the task
	Status string `json:"status,omitempty"`

	// TaskID The id of the task
	TaskID string `json:"taskId,omitempty"`
}
