/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// If authorized, a remote access will expose a port, allowing an access to the device remotely
type OverTheBoxRemoteAccess struct {

	// If the remote access was accepted by the remote user
	Accepted bool `json:"accepted,omitempty"`

	// The date of the remote access demand
	AskDate time.Time `json:"askDate,omitempty"`

	// The user that authorized the remote access
	AuthorizedBy string `json:"authorizedBy,omitempty"`

	ConnectionInfos OverTheBoxRemoteAccessConnectionInfos `json:"connectionInfos,omitempty"`

	// When the remote access will be automatically deleted
	ExpirationDate time.Time `json:"expirationDate,omitempty"`

	// The device's port which will be exposed
	ExposedPort int64 `json:"exposedPort,omitempty"`

	// The id of the remote access
	RemoteAccessId string `json:"remoteAccessId,omitempty"`

	RemoteUserInfos OverTheBoxRemoteAccessUserInfos `json:"remoteUserInfos,omitempty"`

	// Status of the remote access
	Status string `json:"status,omitempty"`
}
