/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// OverTheBoxService Service
type OverTheBoxService struct {

	// CustomerDescription Editable field for customer
	CustomerDescription string `json:"customerDescription,omitempty"`

	GraphEndpoint *OverTheBoxGraphEndpoint `json:"graphEndpoint,omitempty"`

	// ReleaseChannel Release channel of the service
	ReleaseChannel string `json:"releaseChannel,omitempty"`

	// ServiceName The name of the service
	ServiceName string `json:"serviceName,omitempty"`

	// Status The status of the service
	Status string `json:"status,omitempty"`
}
