/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Device
type OverTheBoxDevice struct {

	// Whether or not this device is associated to a service
	Activated bool `json:"activated,omitempty"`

	// The id of the device
	DeviceId string `json:"deviceId,omitempty"`

	// Last time the device has been seen on the provisionning servers
	LastSeen time.Time `json:"lastSeen,omitempty"`

	// Network interfaces of the device
	NetworkInterfaces []OverTheBoxDeviceInterface `json:"networkInterfaces,omitempty"`

	// The public IP of the device
	PublicIp string `json:"publicIp,omitempty"`
}
