/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PaasTimeseriesTag Tag
type PaasTimeseriesTag struct {

	// Key Key
	Key string `json:"key,omitempty"`

	// Value Value
	Value string `json:"value,omitempty"`
}
