/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PaasDatabaseInstanceWhitelist IP whitelisting for your instance
type PaasDatabaseInstanceWhitelist struct {

	// CreationDate Creation date of this whitelist
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// IP The whitelisted IP in your instance
	IP string `json:"ip,omitempty"`

	// LastUpdate The last update date of this whitelist
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// Name Custom name for your Whitelisted IP
	Name string `json:"name,omitempty"`

	// Service Authorize this IP to access service port
	Service bool `json:"service,omitempty"`

	// Sftp Authorize this IP to access sftp port
	Sftp bool `json:"sftp,omitempty"`

	// Status Whitelist status
	Status string `json:"status,omitempty"`

	// TaskID The id of the task working on this object
	TaskID string `json:"taskId,omitempty"`
}
