/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PaasTimeseriesQuota Quota
type PaasTimeseriesQuota struct {

	// Current Current value
	Current int64 `json:"current,omitempty"`

	// Max Max allowed
	Max int64 `json:"max,omitempty"`

	TType string `json:"type,omitempty"`
}
