/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Offers
type PaasDatabaseOffer struct {

	DiskSize PaasDatabaseOfferDiskSize `json:"diskSize,omitempty"`

	// Offer name
	OfferName string `json:"offerName,omitempty"`

	RamSize PaasDatabaseOfferRamSize `json:"ramSize,omitempty"`

	// Offer status
	Status string `json:"status,omitempty"`
}
