/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PaasDatabaseInstance Instances
type PaasDatabaseInstance struct {

	// CreationDate Instance creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	Disk *PaasDatabaseInstanceDisk `json:"disk,omitempty"`

	// Endpoint Instance endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// ImageName Instance image
	ImageName string `json:"imageName,omitempty"`

	// InstanceID Instance uuid
	InstanceID string `json:"instanceId,omitempty"`

	// LastUpdate Instance last update date
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// Name Instance name
	Name string `json:"name,omitempty"`

	// OfferName Instance offer
	OfferName string `json:"offerName,omitempty"`

	// Overquota If set to TRUE, the instance is currently in overquota state
	Overquota bool `json:"overquota,omitempty"`

	RAMSize *PaasDatabaseInstanceRAMSize `json:"ramSize,omitempty"`

	// RegionName Instance region
	RegionName string `json:"regionName,omitempty"`

	// ServicePort Instance service port
	ServicePort int64 `json:"servicePort,omitempty"`

	// SftpPort Instance ftp port
	SftpPort int64 `json:"sftpPort,omitempty"`

	// Status Instance status
	Status string `json:"status,omitempty"`

	// TaskID The task id working on this object
	TaskID string `json:"taskId,omitempty"`
}
