/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PaasTimeseriesKey Key
type PaasTimeseriesKey struct {

	// Description Description
	Description string `json:"description,omitempty"`

	// ID Id
	ID string `json:"id,omitempty"`

	// Permissions List of permissions
	Permissions []string `json:"permissions,omitempty"`

	// Secret Secret part
	Secret string `json:"secret,omitempty"`

	// Tags List of tags
	Tags []*PaasTimeseriesTag `json:"tags,omitempty"`
}
