/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Key
type PaasTimeseriesKey struct {

	// Description
	Description string `json:"description,omitempty"`

	// Id
	Id string `json:"id,omitempty"`

	// List of permissions
	Permissions []string `json:"permissions,omitempty"`

	// Secret part
	Secret string `json:"secret,omitempty"`

	// List of tags
	Tags []PaasTimeseriesTag `json:"tags,omitempty"`
}
