/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Regions
type PaasDatabaseRegion struct {

	// Region continent code
	ContinentCode string `json:"continentCode,omitempty"`

	// Region name
	RegionName string `json:"regionName,omitempty"`

	// Region status
	Status string `json:"status,omitempty"`
}
