/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Project
type PaasTimeseriesProject struct {

	// Description
	Description string `json:"description,omitempty"`

	// Name
	DisplayName string `json:"displayName,omitempty"`

	Region PaasTimeseriesRegion `json:"region,omitempty"`

	// Id
	ServiceName string `json:"serviceName,omitempty"`
}
