/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PaasDatabaseRegion Regions
type PaasDatabaseRegion struct {

	// ContinentCode Region continent code
	ContinentCode string `json:"continentCode,omitempty"`

	// RegionName Region name
	RegionName string `json:"regionName,omitempty"`

	// Status Region status
	Status string `json:"status,omitempty"`
}
