/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PackXdslTask Describes the current status of a task
type PackXdslTask struct {
	Function string `json:"function,omitempty"`

	ID int64 `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	UpdateDate *time.Time `json:"updateDate,omitempty"`
}
