/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Option of Offer
type PackXdslMigrationOfferServiceToDelete struct {

	// Type of the service
	Service string `json:"service,omitempty"`

	// Type of the service to delete
	Type_ string `json:"type,omitempty"`
}
