/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PackXdslSiteBuilderStartServicesPost ...
type PackXdslSiteBuilderStartServicesPost struct {
	Domain string `json:"domain,omitempty"`

	Subdomain string `json:"subdomain,omitempty"`

	TemplateID int64 `json:"templateId,omitempty"`
}
