/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// An offer
type PackXdslAddressMoveOffer struct {

	Address XdslEligibilityAddress `json:"address,omitempty"`

	// The estimated download synchronisation in kbps
	EstimatedDownload int64 `json:"estimatedDownload,omitempty"`

	// The estimated upload synchronisation in kbps
	EstimatedUpload int64 `json:"estimatedUpload,omitempty"`

	// Detailed information about the sections between the DSLAM and the telephone jack
	LineSectionsLength []XdslLineSectionLength `json:"lineSectionsLength,omitempty"`

	// The status of the landline
	LineStatus string `json:"lineStatus,omitempty"`

	MeetingSlots XdslEligibilityMeetingSlots `json:"meetingSlots,omitempty"`

	// The NRA of the landline
	Nra string `json:"nra,omitempty"`

	// The code of the offer
	OfferCode string `json:"offerCode,omitempty"`

	Portability XdslEligibilityPortability `json:"portability,omitempty"`

	Price OrderPrice `json:"price,omitempty"`

	// Status of the request
	Provider string `json:"provider,omitempty"`

	// Whether this is a reseller offer or not
	Reseller bool `json:"reseller,omitempty"`

	// The download synchronisation in kbps
	SyncDownload int64 `json:"syncDownload,omitempty"`

	// The upload synchronisation in kbps
	SyncUpload int64 `json:"syncUpload,omitempty"`

	// DSL technology
	Type_ string `json:"type,omitempty"`

	// The unbundling type
	Unbundling string `json:"unbundling,omitempty"`
}
