/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Eligibility
type PackXdslAddressMoveEligibility struct {

	KeepCurrentPortability XdslEligibilityPortability `json:"keepCurrentPortability,omitempty"`

	// The available offers at this address
	Offers []PackXdslAddressMoveOffer `json:"offers,omitempty"`
}
