/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PackXdslVOIPLineServicesPost ...
type PackXdslVOIPLineServicesPost struct {
	HardwareNames []string `json:"hardwareNames,omitempty"`

	MondialRelayID string `json:"mondialRelayId,omitempty"`

	ShippingID string `json:"shippingId,omitempty"`
}
