/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Hubic service
type PackXdslHubic struct {

	// Size of the hubic account in bytes
	Bytes int64 `json:"bytes,omitempty"`

	Domain string `json:"domain,omitempty"`

	// Human readable size of the hubic account
	Size string `json:"size,omitempty"`

	// Voucher to enter on HubiC website to activate the account
	Voucher string `json:"voucher,omitempty"`
}
