/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PackXdslResiliationTerms Show the resiliation terms
type PackXdslResiliationTerms struct {
	Due *OrderPrice `json:"due,omitempty"`

	// EngageDate Date until which the customer is engaged
	EngageDate *time.Time `json:"engageDate,omitempty"`

	// MinResiliationDate Minimum date at which the pack can be resiliated
	MinResiliationDate *time.Time `json:"minResiliationDate,omitempty"`

	// ResiliationDate Date at which the pack will be resiliated
	ResiliationDate *time.Time `json:"resiliationDate,omitempty"`

	// ResiliationReasons List of available resiliation reasons
	ResiliationReasons []string `json:"resiliationReasons,omitempty"`
}
