/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SiteBuilder template infos
type PackXdslSiteBuilderTemplate struct {

	BkId int64 `json:"bkId,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	PreviewImg string `json:"previewImg,omitempty"`

	Reference string `json:"reference,omitempty"`

	ThumbImage string `json:"thumbImage,omitempty"`
}
