/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PackXdslUnpackTerms Terms to unpack services
type PackXdslUnpackTerms struct {

	// IsAllowed Tells whether or not the service can be unpacked
	IsAllowed bool `json:"isAllowed,omitempty"`

	Price *OrderPrice `json:"price,omitempty"`

	// RenewPeriod Renew period in month of the service
	RenewPeriod float64 `json:"renewPeriod,omitempty"`

	RenewPrice *OrderPrice `json:"renewPrice,omitempty"`
}
