/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// cloud archives sessions
type PcaSession struct {

	// Session end date
	EndDate time.Time `json:"endDate,omitempty"`

	// Session ID
	Id string `json:"id,omitempty"`

	// This is your login
	Login string `json:"login,omitempty"`

	// Session friendly name
	Name string `json:"name,omitempty"`

	// Session size, in bytes
	Size int64 `json:"size,omitempty"`

	// IP session was made from
	SrcIp string `json:"srcIp,omitempty"`

	// Session start date
	StartDate time.Time `json:"startDate,omitempty"`

	// Session state
	State string `json:"state,omitempty"`
}
