/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PcaTask cloud archives tasks
type PcaTask struct {

	// Comment Task comments
	Comment string `json:"comment,omitempty"`

	// Function Task function
	Function string `json:"function,omitempty"`

	// ID Task ID
	ID string `json:"id,omitempty"`

	// IPAddress Host used for task
	IPAddress string `json:"ipAddress,omitempty"`

	// Login Task login
	Login string `json:"login,omitempty"`

	// Status Task status
	Status string `json:"status,omitempty"`

	// TodoDate Task date
	TodoDate *time.Time `json:"todoDate,omitempty"`
}
