/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// PcsAccount PCS Infrastructure
type PcsAccount struct {
	CreationDate *time.Time `json:"creationDate,omitempty"`

	Domain string `json:"domain,omitempty"`

	UserName string `json:"userName,omitempty"`
}
