/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// RegistryInputUser A registry user account
type RegistryInputUser struct {

	// Description A general description of the user account
	Description string `json:"description,omitempty"`
}
