/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// RegistryUser A registry user account
type RegistryUser struct {

	// CreatedAt Date of the resource creation
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description A general description of the user account
	Description bool `json:"description,omitempty"`

	// ID The user id
	ID string `json:"id,omitempty"`

	// Status The status of the user
	Status string `json:"status,omitempty"`

	// UpdatedAt Date of the resource last update
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// Username The user name
	Username string `json:"username,omitempty"`
}
