/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// RegistryInputPermissions Permissions of a user over a namespace
type RegistryInputPermissions struct {

	// CanRead Whether a user can read images on the namespace
	CanRead bool `json:"canRead,omitempty"`

	// CanWrite Whether a user can create images on the namespace
	CanWrite bool `json:"canWrite,omitempty"`

	// IsAdmin Whether a user can delete images on the namespace
	IsAdmin bool `json:"isAdmin,omitempty"`

	// Status The status of the permission
	Status string `json:"status,omitempty"`

	// UserID User Id
	UserID string `json:"userId,omitempty"`
}
