/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// ResellerSnapshot Reseller snapshot
type ResellerSnapshot struct {

	// CreationDate Snapshot creation date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// ID Snapshot id
	ID string `json:"id,omitempty"`

	// SnashotName Snapshot name
	SnashotName string `json:"snashotName,omitempty"`

	// TType Snapshot type
	TType string `json:"type,omitempty"`
}
