/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Reseller snapshot
type ResellerSnapshot struct {

	// Snapshot creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Snapshot id
	Id string `json:"id,omitempty"`

	// Snapshot name
	SnashotName string `json:"snashotName,omitempty"`

	// Snapshot type
	Type_ string `json:"type,omitempty"`
}
