/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Reseller task
type ResellerTask struct {

	// Task current step
	CurrentStep string `json:"currentStep,omitempty"`

	// Task expected done date
	ExpectedDoneDate time.Time `json:"expectedDoneDate,omitempty"`

	// Task id
	Id string `json:"id,omitempty"`

	// Task last update date
	LastUpdateDate time.Time `json:"lastUpdateDate,omitempty"`

	// Linked product
	ProductDomain string `json:"productDomain,omitempty"`

	// Task percentage progression
	Progress int64 `json:"progress,omitempty"`

	// Task name
	TaskName string `json:"taskName,omitempty"`

	// Task status
	TaskStatus string `json:"taskStatus,omitempty"`
}
