/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// ResellerTask Reseller task
type ResellerTask struct {

	// CurrentStep Task current step
	CurrentStep string `json:"currentStep,omitempty"`

	// ExpectedDoneDate Task expected done date
	ExpectedDoneDate *time.Time `json:"expectedDoneDate,omitempty"`

	// ID Task id
	ID string `json:"id,omitempty"`

	// LastUpdateDate Task last update date
	LastUpdateDate *time.Time `json:"lastUpdateDate,omitempty"`

	// ProductDomain Linked product
	ProductDomain string `json:"productDomain,omitempty"`

	// Progress Task percentage progression
	Progress int64 `json:"progress,omitempty"`

	// TaskName Task name
	TaskName string `json:"taskName,omitempty"`

	// TaskStatus Task status
	TaskStatus string `json:"taskStatus,omitempty"`
}
