/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Task
type RouterTask struct {

	CreationDate time.Time `json:"creationDate,omitempty"`

	FinishDate time.Time `json:"finishDate,omitempty"`

	Function string `json:"function,omitempty"`

	Id int64 `json:"id,omitempty"`

	Status string `json:"status,omitempty"`
}
