/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Outgoing routes configured inside a Private Link
type RouterPrivateLinkRoute struct {

	CreationDate time.Time `json:"creationDate,omitempty"`

	Id int64 `json:"id,omitempty"`

	// Network allowed to be routed outside
	Network string `json:"network,omitempty"`

	Status string `json:"status,omitempty"`
}
