/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Private Link to another service
type RouterPrivateLink struct {

	CreationDate time.Time `json:"creationDate,omitempty"`

	Id int64 `json:"id,omitempty"`

	// Your memory-friendly name of this private link
	Name string `json:"name,omitempty"`

	// Service name of the other side of this link
	PeerServiceName string `json:"peerServiceName,omitempty"`

	Status string `json:"status,omitempty"`
}
