/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// RouterVpn Virtual Private Network
type RouterVpn struct {

	// ClientIP IP you will be connecting from / NULL (allow all)
	ClientIP string `json:"clientIp,omitempty"`

	// ClientPrivNet Client's private network
	ClientPrivNet string `json:"clientPrivNet,omitempty"`

	ID int64 `json:"id,omitempty"`

	// ServerIP Your VPN server IP
	ServerIP string `json:"serverIp,omitempty"`

	// ServerPrivNet Server's private network
	ServerPrivNet string `json:"serverPrivNet,omitempty"`
}
