/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SaasCsp2ConfigureDomainPost ...
type SaasCsp2ConfigureDomainPost struct {
	Domain string `json:"domain,omitempty"`

	SupportedServices []string `json:"supportedServices,omitempty"`
}
