/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Office licence
type SaasCsp2OfficeLicence struct {

	// License unique identifier
	Id int64 `json:"id,omitempty"`

	// Maximum purchasable license
	Limit int64 `json:"limit,omitempty"`

	// License name
	Name string `json:"name,omitempty"`
}
