/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Office subscription
type SaasCsp2OfficeSubscription struct {

	// Creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// Subscription's unique identifier
	Id int64 `json:"id,omitempty"`

	// Last update date
	LastUpdate time.Time `json:"lastUpdate,omitempty"`

	// License's type id
	LicenseId int64 `json:"licenseId,omitempty"`

	// Number of available licenses
	Quantity int64 `json:"quantity,omitempty"`

	// Subscription's status
	Status string `json:"status,omitempty"`

	// Pending task's unique identifier
	TaskPendingId int64 `json:"taskPendingId,omitempty"`
}
