/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SaasCsp2BillingStatisticsLine Billing statistics line.
type SaasCsp2BillingStatisticsLine struct {

	// LicenceID Id of the Office license.
	LicenceID int64 `json:"licenceId,omitempty"`

	// LicenceName Name of the Office license.
	LicenceName string `json:"licenceName,omitempty"`

	// PeakCount Maximum count of simultaneous activated licences.
	PeakCount int64 `json:"peakCount,omitempty"`
}
