/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// ServiceRenewType Map a possible renew for a specific service
type ServiceRenewType struct {

	// Automatic The service is automatically renewed
	Automatic bool `json:"automatic,omitempty"`

	// DeleteAtExpiration The service will be deleted at expiration
	DeleteAtExpiration bool `json:"deleteAtExpiration,omitempty"`

	// Forced The service forced to be renewed
	Forced bool `json:"forced,omitempty"`

	// Period period of renew in month
	Period int64 `json:"period,omitempty"`
}
