/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SmsHlr Sms operator informations
type SmsHlr struct {

	// Country The country
	Country string `json:"country,omitempty"`

	// CountryCode The countryCode prefix number
	CountryCode string `json:"countryCode,omitempty"`

	// Network The network name
	Network string `json:"network,omitempty"`

	// Operator The operator name
	Operator string `json:"operator,omitempty"`

	// Region The region
	Region string `json:"region,omitempty"`
}
