/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SMS users
type SmsUser struct {

	AlertThresholdInformations SmsAlertThreshold `json:"alertThresholdInformations,omitempty"`

	// URL called when state of a sent SMS changes
	CallBack string `json:"callBack,omitempty"`

	IpRestrictions []string `json:"ipRestrictions,omitempty"`

	// The sms user login
	Login string `json:"login,omitempty"`

	Password string `json:"password,omitempty"`

	QuotaInformations SmsQuota `json:"quotaInformations,omitempty"`

	// URL called when a STOP is received after a receiver replied stop to a SMS
	StopCallBack string `json:"stopCallBack,omitempty"`
}
