/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SmsAccount SMS details
type SmsAccount struct {
	AutomaticRecreditAmount int64 `json:"automaticRecreditAmount,omitempty"`

	// CallBack URL called when state of a sent SMS changes
	CallBack string `json:"callBack,omitempty"`

	// CreditThresholdForAutomaticRecredit Credit threshold after which an automatic recredit is launched
	CreditThresholdForAutomaticRecredit float64 `json:"creditThresholdForAutomaticRecredit,omitempty"`

	CreditsHoldByQuota float64 `json:"creditsHoldByQuota,omitempty"`

	CreditsLeft float64 `json:"creditsLeft,omitempty"`

	Description string `json:"description,omitempty"`

	Name string `json:"name,omitempty"`

	SmsResponse *SmsResponse `json:"smsResponse,omitempty"`

	Status string `json:"status,omitempty"`

	// StopCallBack URL called when a STOP is received after a receiver replied stop to a SMS
	StopCallBack string `json:"stopCallBack,omitempty"`

	Templates *SmsTemplates `json:"templates,omitempty"`

	UserQuantityWithQuota int64 `json:"userQuantityWithQuota,omitempty"`
}
