/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure describing how to manage an sms Response
type SmsResponse struct {

	// Default url callback used for a given response.
	CgiUrl string `json:"cgiUrl,omitempty"`

	ResponseType string `json:"responseType,omitempty"`

	// Automatic notification sent by text in case of customer reply.
	Text string `json:"text,omitempty"`

	TrackingDefaultSmsSender string `json:"trackingDefaultSmsSender,omitempty"`

	TrackingOptions []SmsResponseTrackingOptions `json:"trackingOptions,omitempty"`
}
