/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SmsSender SMS senders
type SmsSender struct {

	// Comment Message sent by the moderator
	Comment string `json:"comment,omitempty"`

	// Description Sender description
	Description string `json:"description,omitempty"`

	// Referer Specify if the sender is custom or not
	Referer string `json:"referer,omitempty"`

	// Sender The sms sender
	Sender string `json:"sender,omitempty"`

	// Status Sender status
	Status string `json:"status,omitempty"`

	// TType Specify the kind of sender
	TType string `json:"type,omitempty"`

	// ValidationMedia Validation media identifier
	ValidationMedia string `json:"validationMedia,omitempty"`
}
