/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// SpareXdslSpare Spare properties
type SpareXdslSpare struct {

	// Brand Modem brand model
	Brand string `json:"brand,omitempty"`

	// MacAddress Mac address
	MacAddress string `json:"macAddress,omitempty"`
}
