/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Closing period for mondial relay point
type SupplyMondialRelayClosingPeriod struct {

	// Ending of closing period
	End time.Time `json:"end,omitempty"`

	// Beginning of closing period
	Start time.Time `json:"start,omitempty"`
}
