/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Telephony API related file hosted
type TelephonyPcsFile struct {

	Filename string `json:"filename,omitempty"`

	Status string `json:"status,omitempty"`

	Url string `json:"url,omitempty"`

	UrlExpirationDatetime time.Time `json:"urlExpirationDatetime,omitempty"`
}
