/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyRateCodeInformation Informations related to the rate code
type TelephonyRateCodeInformation struct {

	// Code The Rsva rate code
	Code string `json:"code,omitempty"`

	PricePerCallWithoutTax *OrderPrice `json:"pricePerCallWithoutTax,omitempty"`

	PricePerMinuteWithoutTax *OrderPrice `json:"pricePerMinuteWithoutTax,omitempty"`
}
