/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonySchedulerEvent Scheduled event
type TelephonySchedulerEvent struct {

	// Categories The category of the event
	Categories string `json:"categories,omitempty"`

	// DateEnd The ending date of the event
	DateEnd *time.Time `json:"dateEnd,omitempty"`

	// DateStart The beginning date of the event
	DateStart *time.Time `json:"dateStart,omitempty"`

	Description string `json:"description,omitempty"`

	Title string `json:"title,omitempty"`

	// UID The unique ICS event identifier
	UID string `json:"uid,omitempty"`
}
