/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Event of a conference (participant left/join)
type TelephonyConferenceHistoryEvent struct {

	// The caller id of the participant
	Callerid string `json:"callerid,omitempty"`

	// The date of the conference event
	Date time.Time `json:"date,omitempty"`

	// The nature of the event : left/join
	Type_ string `json:"type,omitempty"`
}
