/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Advanced diagnostic of the voice call
type TelephonyCallDiagnostics struct {

	// The MOS call quality report
	CallQuality []TelephonyCallDiagnosticCallQuality `json:"callQuality,omitempty"`

	// The Call details records information
	Cdrs []TelephonyCallDiagnosticCdrs `json:"cdrs,omitempty"`

	// The relevant informations in anormal behaviors
	Reporting []TelephonyCallDiagnosticReporting `json:"reporting,omitempty"`

	// Sip signal packets during the call and last registers
	Sip []TelephonyCallDiagnosticSip `json:"sip,omitempty"`

	// Todo if datas are being to be loaded in cache. done when datas are available
	Status string `json:"status,omitempty"`
}
