/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyCallsGenerated Automatic Call made by Call Generator on this line
type TelephonyCallsGenerated struct {

	// AnswerDatetime answer date
	AnswerDatetime *time.Time `json:"answerDatetime,omitempty"`

	// Application Application and dialplan running for call
	Application string `json:"application,omitempty"`

	// ApplicationResult end status of application
	ApplicationResult string `json:"applicationResult,omitempty"`

	// BillingNumber billingNumber (service used)
	BillingNumber string `json:"billingNumber,omitempty"`

	// CallCreatedDatetime creation date of the call
	CallCreatedDatetime *time.Time `json:"callCreatedDatetime,omitempty"`

	// CallDuration call duration on seconds
	CallDuration int64 `json:"callDuration,omitempty"`

	// Callee number called
	Callee string `json:"callee,omitempty"`

	// Caller number where the call come from
	Caller string `json:"caller,omitempty"`

	// Dtmf DTMF received during the call separate by commas
	Dtmf string `json:"dtmf,omitempty"`

	// HangupCause hangup cause
	HangupCause string `json:"hangupCause,omitempty"`

	// HangupDatetime hangup date
	HangupDatetime *time.Time `json:"hangupDatetime,omitempty"`

	// IDentifier Generated call identifier
	IDentifier string `json:"identifier,omitempty"`

	// TransferFrom original call uuid if it's a transfer
	TransferFrom string `json:"transferFrom,omitempty"`

	// UUID unique call id
	UUID string `json:"uuid,omitempty"`
}
