/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Plug & Phone
type TelephonyPhone struct {

	// Brand name
	Brand string `json:"brand,omitempty"`

	// The phone description
	Description string `json:"description,omitempty"`

	// Mac Address
	MacAddress string `json:"macAddress,omitempty"`

	// Maximum number of lines managed by a phone
	Maxline int64 `json:"maxline,omitempty"`

	// The ip restriction of your MGCP phone
	MgcpIpRestriction string `json:"mgcpIpRestriction,omitempty"`

	// Current phone properties
	PhoneConfiguration []TelephonyPhoneConfigurationProperty `json:"phoneConfiguration,omitempty"`

	// Phone protocol
	Protocol string `json:"protocol,omitempty"`
}
