/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Conference realtime informations structure
type TelephonyConferenceInformations struct {

	// The date when the conference began
	DateStart time.Time `json:"dateStart,omitempty"`

	// Whether or not the conference room is locked
	Locked bool `json:"locked,omitempty"`

	// The current participants count in your conference room
	MembersCount int64 `json:"membersCount,omitempty"`
}
