/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyTones Line tones
type TelephonyTones struct {

	// CallWaiting Tone played when caller is waiting in queue
	CallWaiting string `json:"callWaiting,omitempty"`

	// EndCall Tone played when callee is ending call
	EndCall string `json:"endCall,omitempty"`

	// OnHold Tone played when caller is put on hold
	OnHold string `json:"onHold,omitempty"`

	// Ringback Ringback tone
	Ringback string `json:"ringback,omitempty"`
}
