/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyOvhPabxDialplan Dialplan
type TelephonyOvhPabxDialplan struct {

	// AnonymousRejection Reject (hangup) anonymous calls
	AnonymousRejection bool `json:"anonymousRejection,omitempty"`

	DialplanID int64 `json:"dialplanId,omitempty"`

	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// Name The dialplan name
	Name string `json:"name,omitempty"`

	// ShowCallerNumber The presented number when bridging calls
	ShowCallerNumber string `json:"showCallerNumber,omitempty"`

	// TransferTimeout The timeout (in seconds) when bridging calls
	TransferTimeout int64 `json:"transferTimeout,omitempty"`
}
