/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Relevant informations about reset code
type TelephonyResetPhoneCodeInfo struct {

	// Activation code
	ActivationCode string `json:"activationCode,omitempty"`

	// Key book url
	KeyBook string `json:"keyBook,omitempty"`

	// Server url
	ServerURL string `json:"serverURL,omitempty"`
}
