/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Portability informations
type TelephonyPortability struct {

	// The billing account where the numbers will be inserted
	BillingAccount string `json:"billingAccount,omitempty"`

	// The portability's creation date
	CreationDate time.Time `json:"creationDate,omitempty"`

	// The date when the portability will be done and when numbers will be ported
	DesiredExecutionDate time.Time `json:"desiredExecutionDate,omitempty"`

	// The ID of the portability
	Id int64 `json:"id,omitempty"`

	// The list of numbers that is going to be ported
	NumbersList []string `json:"numbersList,omitempty"`

	// The operator that currently holds the numbers
	Operator string `json:"operator,omitempty"`

	// The ID of the portability order
	OrderId int64 `json:"orderId,omitempty"`

	// Country that defines the portability kind
	PortabilityCountry string `json:"portabilityCountry,omitempty"`
}
