/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyOvhPabxHuntingAgentQueue Agent assigned to a queue
type TelephonyOvhPabxHuntingAgentQueue struct {
	AgentID int64 `json:"agentId,omitempty"`

	// Position The position in the queue
	Position int64 `json:"position,omitempty"`

	QueueID int64 `json:"queueId,omitempty"`
}
