/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyOvhPabxHuntingQueueAgentPost ...
type TelephonyOvhPabxHuntingQueueAgentPost struct {
	Position int64 `json:"position,omitempty"`

	QueueID int64 `json:"queueId,omitempty"`
}
