/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyLineClick2CallUserPost ...
type TelephonyLineClick2CallUserPost struct {
	Login string `json:"login,omitempty"`

	Password string `json:"password,omitempty"`
}
