/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Call delivery record
type TelephonyVoiceConsumption struct {

	Called string `json:"called,omitempty"`

	Calling string `json:"calling,omitempty"`

	ConsumptionId int64 `json:"consumptionId,omitempty"`

	// Country suffix destination
	CountrySuffix string `json:"countrySuffix,omitempty"`

	CreationDatetime time.Time `json:"creationDatetime,omitempty"`

	// Description of the destination
	Designation string `json:"designation,omitempty"`

	DestinationType string `json:"destinationType,omitempty"`

	Dialed string `json:"dialed,omitempty"`

	Duration int64 `json:"duration,omitempty"`

	// Information about hangup cause
	HangupNature string `json:"hangupNature,omitempty"`

	PlanType string `json:"planType,omitempty"`

	PriceWithoutTax OrderPrice `json:"priceWithoutTax,omitempty"`

	WayType string `json:"wayType,omitempty"`
}
