/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyTimeConditionConditionPost ...
type TelephonyTimeConditionConditionPost struct {
	Day string `json:"day,omitempty"`

	HourBegin string `json:"hourBegin,omitempty"`

	HourEnd string `json:"hourEnd,omitempty"`

	Policy string `json:"policy,omitempty"`
}
