/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Current Return Merchandise Authorisation
type TelephonyRma struct {

	// Creation datetime of the return merchandise authorisation ticket
	CreationDatetime time.Time `json:"creationDatetime,omitempty"`

	// Merchandise reference
	EquipmentReference string `json:"equipmentReference,omitempty"`

	// Return merchandise authorisation identifier
	Id string `json:"id,omitempty"`

	// New merchandise brand in case of exchange
	NewMerchandise string `json:"newMerchandise,omitempty"`

	// Offer type of the new merchandise in case of exchange
	OfferTypeNew string `json:"offerTypeNew,omitempty"`

	// Offer type of the return merchandise
	OfferTypeOld string `json:"offerTypeOld,omitempty"`

	// Reception datetime of the return merchandise authorisation ticket
	ReceptionDatetime time.Time `json:"receptionDatetime,omitempty"`

	ShippingContact TelephonyContact `json:"shippingContact,omitempty"`

	// Return merchandise authorisation step
	Status string `json:"status,omitempty"`

	// Termination datetime of the return merchandise authorisation ticket
	TerminationDatetime time.Time `json:"terminationDatetime,omitempty"`

	// Typology process of merchandise return
	Type_ string `json:"type,omitempty"`
}
