/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonySearchService Informations related to a telephony service
type TelephonySearchService struct {

	// BillingAccount The billing account of the service
	BillingAccount string `json:"billingAccount,omitempty"`

	// Domain The service domain
	Domain string `json:"domain,omitempty"`

	// TType The offer description
	TType string `json:"type,omitempty"`
}
