/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonySpecificNumber Specific number available
type TelephonySpecificNumber struct {

	// IsPremium Set if number is premium
	IsPremium bool `json:"isPremium,omitempty"`

	// Number The number
	Number string `json:"number,omitempty"`
}
