/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Contact informations structure
type TelephonyContact struct {

	// Contact address
	Address string `json:"address,omitempty"`

	// Contact city
	City string `json:"city,omitempty"`

	// Contact country
	Country string `json:"country,omitempty"`

	Email string `json:"email,omitempty"`

	// Contact firstname
	Firstname string `json:"firstname,omitempty"`

	// Contact name
	Name string `json:"name,omitempty"`

	// Contact organisation
	Organisation string `json:"organisation,omitempty"`

	// Contact phone
	Phone string `json:"phone,omitempty"`

	// Contact zip
	Zip string `json:"zip,omitempty"`
}
