/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// A ip value associated to a datetime
type TelephonyDatetimeAndIpvalue struct {

	Datetime time.Time `json:"datetime,omitempty"`

	Ip string `json:"ip,omitempty"`
}
