/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyPortabilityStepDuration Represent the delay between two portability steps
type TelephonyPortabilityStepDuration struct {

	// Quantity The quantity of delay
	Quantity int64 `json:"quantity,omitempty"`

	// Unit The delay's unit
	Unit string `json:"unit,omitempty"`
}
