/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyPortabilityStep A step in the portability process
type TelephonyPortabilityStep struct {

	// Description A brief description of the step
	Description string `json:"description,omitempty"`

	// DoneDate The date when this step was done
	DoneDate *time.Time `json:"doneDate,omitempty"`

	Duration *TelephonyPortabilityStepDuration `json:"duration,omitempty"`

	Infos *TelephonyPortabilityStepInfos `json:"infos,omitempty"`

	// Name The name of the portability step
	Name string `json:"name,omitempty"`

	// Status Indicates if the step is to do, currently doing or done
	Status string `json:"status,omitempty"`
}
