/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Informations about a SIP registration (i.e. IP, port, User-Agent...)
type TelephonyRegistrationInformations struct {

	// SIP registration's date
	Datetime time.Time `json:"datetime,omitempty"`

	// SIP registration's domain
	Domain string `json:"domain,omitempty"`

	// SIP registration's IP
	Ip string `json:"ip,omitempty"`

	// SIP registration's port
	Port int64 `json:"port,omitempty"`

	// SIP registration's User-Agent
	UserAgent string `json:"userAgent,omitempty"`
}
