/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

type TelephonyDefaultSipDomains struct {

	// Country
	Country string `json:"country,omitempty"`

	// Current SIP domain
	CurrentDomain string `json:"currentDomain,omitempty"`

	// List of available SIP domains
	List []string `json:"list,omitempty"`

	// Type of the VoIP product concerned
	ProductType string `json:"productType,omitempty"`
}
