/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// List past conferences on your number
type TelephonyConferenceHistory struct {

	// The count of connections to the conference
	CountConnections int64 `json:"countConnections,omitempty"`

	// The count of unique participants of the conference
	CountParticipants int64 `json:"countParticipants,omitempty"`

	// The date the conference began
	DateBegin time.Time `json:"dateBegin,omitempty"`

	// The date the conference end
	DateEnd time.Time `json:"dateEnd,omitempty"`

	// The duration of the conference in seconds
	Duration int64 `json:"duration,omitempty"`

	// The events of the conference (participants joining/left)
	Events []TelephonyConferenceHistoryEvent `json:"events,omitempty"`

	// The id of the conference history
	Id int64 `json:"id,omitempty"`

	// The audio record url if you set recording
	RecordUrl string `json:"recordUrl,omitempty"`
}
