/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyAliasesChangeContactPost ...
type TelephonyAliasesChangeContactPost struct {
	ContactAdmin string `json:"contactAdmin,omitempty"`

	ContactBilling string `json:"contactBilling,omitempty"`

	ContactTech string `json:"contactTech,omitempty"`
}
