/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyLineClick2CallUserClick2CallPost ...
type TelephonyLineClick2CallUserClick2CallPost struct {
	CalledNumber string `json:"calledNumber,omitempty"`

	CallingNumber string `json:"callingNumber,omitempty"`
}
