/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

type TelephonyFaxSettingsSendFaxPost struct {

	DateSchedule time.Time `json:"dateSchedule,omitempty"`

	PdfUrl string `json:"pdfUrl,omitempty"`

	Recipients []string `json:"recipients,omitempty"`
}
