/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyPhone Plug & Phone
type TelephonyPhone struct {

	// Brand Brand name
	Brand string `json:"brand,omitempty"`

	// Description The phone description
	Description string `json:"description,omitempty"`

	// MacAddress Mac Address
	MacAddress string `json:"macAddress,omitempty"`

	// Maxline Maximum number of lines managed by a phone
	Maxline int64 `json:"maxline,omitempty"`

	// MgcpIPRestriction The ip restriction of your MGCP phone
	MgcpIPRestriction string `json:"mgcpIpRestriction,omitempty"`

	// PhoneConfiguration Current phone properties
	PhoneConfiguration []*TelephonyPhoneConfigurationProperty `json:"phoneConfiguration,omitempty"`

	// Protocol Phone protocol
	Protocol string `json:"protocol,omitempty"`
}
