/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Agent assigned to a queue
type TelephonyOvhPabxHuntingAgentQueue struct {

	AgentId int64 `json:"agentId,omitempty"`

	// The position in the queue
	Position int64 `json:"position,omitempty"`

	QueueId int64 `json:"queueId,omitempty"`
}
