/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Screenlist condition
type TelephonyOvhPabxDialplanExtensionConditionScreenList struct {

	// Screenlist based on the presented caller number
	CallerIdNumber string `json:"callerIdNumber,omitempty"`

	ConditionId int64 `json:"conditionId,omitempty"`

	// Screenlist based on the destination number
	DestinationNumber string `json:"destinationNumber,omitempty"`

	// Type of screenlist
	ScreenListType string `json:"screenListType,omitempty"`
}
