/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyFaxCampaign Fax campaigns
type TelephonyFaxCampaign struct {

	// CountFailed The count of failed faxes in the campaign
	CountFailed int64 `json:"countFailed,omitempty"`

	// CountSuccess The count of success faxes in the campaign
	CountSuccess int64 `json:"countSuccess,omitempty"`

	// CountTotal The total count of faxes in the campaign
	CountTotal int64 `json:"countTotal,omitempty"`

	// DateEnd The end date of the fax campaign
	DateEnd *time.Time `json:"dateEnd,omitempty"`

	// DateStart The start date of the fax campaign
	DateStart *time.Time `json:"dateStart,omitempty"`

	// ID The id of the fax campaign
	ID int64 `json:"id,omitempty"`

	// Name The name of the fax campaign
	Name string `json:"name,omitempty"`

	// Reference The reference of the fax campaign
	Reference string `json:"reference,omitempty"`

	// Status The status of the fax campaign
	Status string `json:"status,omitempty"`
}
