/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyVoicemailMessages Voicemail message
type TelephonyVoicemailMessages struct {

	// Callee Callee number in international format
	Callee string `json:"callee,omitempty"`

	// Caller Caller number in international format
	Caller string `json:"caller,omitempty"`

	// CreationDatetime Message datetime creation
	CreationDatetime *time.Time `json:"creationDatetime,omitempty"`

	// Dir Voicemessage directory
	Dir string `json:"dir,omitempty"`

	// Duration Message duration (in seconds)
	Duration int64 `json:"duration,omitempty"`

	// ID Uniq voicemail message identifier
	ID int64 `json:"id,omitempty"`
}
