/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyMiniPabxHunting MiniPabx Hunting
type TelephonyMiniPabxHunting struct {

	// AnonymousCallRejection Reject anonymous calls
	AnonymousCallRejection bool `json:"anonymousCallRejection,omitempty"`

	Name string `json:"name,omitempty"`

	// NumberOfCalls Number of simultaneous calls
	NumberOfCalls int64 `json:"numberOfCalls,omitempty"`

	// OnHoldTimer The maximum waiting time in the calls queue
	OnHoldTimer int64 `json:"onHoldTimer,omitempty"`

	Pattern string `json:"pattern,omitempty"`

	Strategy string `json:"strategy,omitempty"`

	// ToneOnClosure True if the tone on closure is enabled
	ToneOnClosure bool `json:"toneOnClosure,omitempty"`

	// ToneOnHold True if the tone on hold is enabled
	ToneOnHold bool `json:"toneOnHold,omitempty"`

	// ToneRingback True if the ring back tone is enabled
	ToneRingback bool `json:"toneRingback,omitempty"`
}
