/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// TelephonyContact Contact informations structure
type TelephonyContact struct {

	// Address Contact address
	Address string `json:"address,omitempty"`

	// City Contact city
	City string `json:"city,omitempty"`

	// Country Contact country
	Country string `json:"country,omitempty"`

	Email string `json:"email,omitempty"`

	// Firstname Contact firstname
	Firstname string `json:"firstname,omitempty"`

	// Name Contact name
	Name string `json:"name,omitempty"`

	// Organisation Contact organisation
	Organisation string `json:"organisation,omitempty"`

	// Phone Contact phone
	Phone string `json:"phone,omitempty"`

	// Zip Contact zip
	Zip string `json:"zip,omitempty"`
}
