/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// IVR menu entry
type TelephonyOvhPabxMenuEntry struct {

	// The action triggered by the DTMF
	Action string `json:"action,omitempty"`

	// The additionnal parameter of the action
	ActionParam string `json:"actionParam,omitempty"`

	// The DTMF that triggers the action
	Dtmf string `json:"dtmf,omitempty"`

	EntryId int64 `json:"entryId,omitempty"`

	// The position of the entry in the menu
	Position int64 `json:"position,omitempty"`
}
