/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// TelephonyRma Current Return Merchandise Authorisation
type TelephonyRma struct {

	// CreationDatetime Creation datetime of the return merchandise authorisation ticket
	CreationDatetime *time.Time `json:"creationDatetime,omitempty"`

	// EquipmentReference Merchandise reference
	EquipmentReference string `json:"equipmentReference,omitempty"`

	// ID Return merchandise authorisation identifier
	ID string `json:"id,omitempty"`

	// NewMerchandise New merchandise brand in case of exchange
	NewMerchandise string `json:"newMerchandise,omitempty"`

	// OfferTypeNew Offer type of the new merchandise in case of exchange
	OfferTypeNew string `json:"offerTypeNew,omitempty"`

	// OfferTypeOld Offer type of the return merchandise
	OfferTypeOld string `json:"offerTypeOld,omitempty"`

	// ReceptionDatetime Reception datetime of the return merchandise authorisation ticket
	ReceptionDatetime *time.Time `json:"receptionDatetime,omitempty"`

	ShippingContact *TelephonyContact `json:"shippingContact,omitempty"`

	// Status Return merchandise authorisation step
	Status string `json:"status,omitempty"`

	// TerminationDatetime Termination datetime of the return merchandise authorisation ticket
	TerminationDatetime *time.Time `json:"terminationDatetime,omitempty"`

	// TType Typology process of merchandise return
	TType string `json:"type,omitempty"`
}
