/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Timeseries project
type TimeseriesProject struct {

	// description of your project
	Description string `json:"description,omitempty"`

	// name of your project
	DisplayName string `json:"displayName,omitempty"`

	// subscribed offer
	OfferId string `json:"offerId,omitempty"`

	// region where your data are located
	RegionId string `json:"regionId,omitempty"`

	// timeseries Project id
	ServiceName string `json:"serviceName,omitempty"`

	// project status
	Status string `json:"status,omitempty"`
}
