/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about a disk of a VPS Virtual Machine
type VpsDisk struct {

	BandwidthLimit int64 `json:"bandwidthLimit,omitempty"`

	Id int64 `json:"id,omitempty"`

	// The low disk free space threshold in MiB
	LowFreeSpaceThreshold int64 `json:"lowFreeSpaceThreshold,omitempty"`

	// The monitoring state of this disk
	Monitoring bool `json:"monitoring,omitempty"`

	Size int64 `json:"size,omitempty"`

	State string `json:"state,omitempty"`

	Type_ string `json:"type,omitempty"`
}
