/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Informations about a VPS Veeam restore points
type VpsVeeamRestorePoint struct {

	// The restore point's creation time
	CreationTime time.Time `json:"creationTime,omitempty"`

	// The restore point's id
	Id int64 `json:"id,omitempty"`
}
