/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Service states for an Ip
type VpsIpServiceStatus struct {

	Dns VpsIpServiceStatusService `json:"dns,omitempty"`

	Http VpsIpServiceStatusService `json:"http,omitempty"`

	Https VpsIpServiceStatusService `json:"https,omitempty"`

	Ping string `json:"ping,omitempty"`

	Smtp VpsIpServiceStatusService `json:"smtp,omitempty"`

	Ssh VpsIpServiceStatusService `json:"ssh,omitempty"`

	Tools string `json:"tools,omitempty"`
}
