/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about an IP address for a VPS Virtual Machine
type VpsIp struct {

	Gateway string `json:"gateway,omitempty"`

	Geolocation string `json:"geolocation,omitempty"`

	// The effective ip address of the Ip object
	IpAddress string `json:"ipAddress,omitempty"`

	MacAddress string `json:"macAddress,omitempty"`

	Reverse string `json:"reverse,omitempty"`

	Type_ string `json:"type,omitempty"`

	Version string `json:"version,omitempty"`
}
