/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// PublicCloud project in vrack
type VrackCloudProject struct {

	// publicCloud project
	Project string `json:"project,omitempty"`

	// vrack name
	Vrack string `json:"vrack,omitempty"`
}
