/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// vrack dedicated connect interface
type VrackDedicatedConnect struct {

	// A name for your dedicatedConnect link
	Name string `json:"name,omitempty"`
}
