/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// VrackPccDatacenter vrack datacenter interface
type VrackPccDatacenter struct {

	// Datacenter Your dedicatedCloud datacenter name
	Datacenter string `json:"datacenter,omitempty"`

	// DedicatedCloud Your dedicatedCloud name
	DedicatedCloud string `json:"dedicatedCloud,omitempty"`

	// Vrack vrack name
	Vrack string `json:"vrack,omitempty"`
}
