/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// A structure giving all dedicated server interfaces allowed for this vrack
type VrackAllowedDedicatedServerInterfaces struct {

	// the name of dedicatedServer
	DedicatedServer string `json:"dedicatedServer,omitempty"`

	// the unique identifier of dedicatedServerInterface
	DedicatedServerInterface string `json:"dedicatedServerInterface,omitempty"`

	// the name of dedicatedServerInterface
	Name string `json:"name,omitempty"`
}
