/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// interface between legacy vrack (vrackXXXX) and vrack (pn-XXXX)
type VrackLegacyVrack struct {

	// your legacy vrack service
	LegacyVrack string `json:"legacyVrack,omitempty"`

	// vlan to set on legacy vrack equipments
	VlanId int64 `json:"vlanId,omitempty"`
}
