/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// VrackIP IP block in vrack
type VrackIP struct {

	// Gateway Your gateway
	Gateway string `json:"gateway,omitempty"`

	// IP Your IP block
	IP string `json:"ip,omitempty"`

	// Zone Where you want your block announced on the network
	Zone string `json:"zone,omitempty"`
}
