/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// XdslDeviceModemInfo Describe device informations of a Modem
type XdslDeviceModemInfo struct {

	// Brand Modem brand
	Brand string `json:"brand,omitempty"`

	// IP Modem ip address
	IP string `json:"ip,omitempty"`

	// LastUpdate Time of last information refresh
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// MacAddress Modem mac address
	MacAddress string `json:"macAddress,omitempty"`

	// Model Modem type of model
	Model string `json:"model,omitempty"`

	// Oui Organizational Unique Identifier
	Oui string `json:"oui,omitempty"`

	// OverEthernet Protocol used for connection
	OverEthernet string `json:"overEthernet,omitempty"`

	// PppLogin login used for ppp protocol
	PppLogin string `json:"pppLogin,omitempty"`

	// Serial Modem serial key
	Serial string `json:"serial,omitempty"`

	// SoftVersion Software Version
	SoftVersion string `json:"softVersion,omitempty"`
}
