/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Represents a street
type XdslEligibilityStreet struct {

	// The name of the street
	Name string `json:"name,omitempty"`

	// The identifier of the street
	RivoliCode string `json:"rivoliCode,omitempty"`
}
