/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// Informations about the extra IP range during address move
type XdslExtraIpRangeMove struct {

	// Date of the migration
	Date time.Time `json:"date,omitempty"`

	// IP range to migrate
	IpRange string `json:"ipRange,omitempty"`

	// Access where the IP range will be moved to
	MoveTo string `json:"moveTo,omitempty"`
}
