/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Xdsl Settings
type XdslSetting struct {

	// Send the modem as soon as possible, do not wait the xdsl line to be active
	ResellerFastModemShipping bool `json:"resellerFastModemShipping,omitempty"`
}
