/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// XdslLineDiagnosticAnswers Customer answers for line diagnostic
type XdslLineDiagnosticAnswers struct {

	// Comment comment will contains all informations needed for intervention and about your access problem
	Comment string `json:"comment,omitempty"`

	// ConditionsAccepted customer knows that he can be charged (150 euros HT) if he is responsible for the problem or if tests have not been done correctly ?
	ConditionsAccepted bool `json:"conditionsAccepted,omitempty"`

	// ContactPhone customer's phone number
	ContactPhone string `json:"contactPhone,omitempty"`

	// DatetimeOfAppearance approximative datetime of problem happening
	DatetimeOfAppearance *time.Time `json:"datetimeOfAppearance,omitempty"`

	// EndAfternoonHours afternoon closing informations or time for the site
	EndAfternoonHours string `json:"endAfternoonHours,omitempty"`

	// EndMorningHours morning closing informations or time for the site
	EndMorningHours string `json:"endMorningHours,omitempty"`

	// FollowBySms indicate if customer wants to be informed by sms
	FollowBySms bool `json:"followBySms,omitempty"`

	// HasModemKeptSynchronization Has modem kept his synchronization during line port reset ?
	HasModemKeptSynchronization bool `json:"hasModemKeptSynchronization,omitempty"`

	// IDAppointment id of appointment chosen (\"possibleValues\" contains choices list with id)
	IDAppointment int64 `json:"idAppointment,omitempty"`

	// IndividualSite is non-professional site ?
	IndividualSite bool `json:"individualSite,omitempty"`

	// ModemIsSynchronized Is modem synchronized ? (whatever internet connection)
	ModemIsSynchronized bool `json:"modemIsSynchronized,omitempty"`

	// ModemMac modem mac address
	ModemMac string `json:"modemMac,omitempty"`

	// ModemStillSynchronized Modem still synchronized ? Please check once again.
	ModemStillSynchronized bool `json:"modemStillSynchronized,omitempty"`

	// ModemType modem brand and reference
	ModemType string `json:"modemType,omitempty"`

	// ResolvedAfterTests is access problem solved ?
	ResolvedAfterTests bool `json:"resolvedAfterTests,omitempty"`

	// SecureSite is secure site ?
	SecureSite bool `json:"secureSite,omitempty"`

	// SeveralInternetConnections Has customer several internal connections ? (on the same place)
	SeveralInternetConnections bool `json:"severalInternetConnections,omitempty"`

	// SiteClosedDays days or period where site access is not possible
	SiteClosedDays string `json:"siteClosedDays,omitempty"`

	// SiteDigicode digicode for site entrance
	SiteDigicode string `json:"siteDigicode,omitempty"`

	// SiteOpening site opening hours or informations
	SiteOpening string `json:"siteOpening,omitempty"`

	// StartAfternoonHours afternoon opening informations or time for the site
	StartAfternoonHours string `json:"startAfternoonHours,omitempty"`

	// StartMorningHours morning opening informations or time for the site
	StartMorningHours string `json:"startMorningHours,omitempty"`
}
