/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Represents an address
type XdslEligibilityAddress struct {

	// The name of the building, if any
	Building string `json:"building,omitempty"`

	City XdslEligibilityCity `json:"city,omitempty"`

	// The identifier of the door, if any
	Door string `json:"door,omitempty"`

	// The identifier of the floor, if any
	Floor string `json:"floor,omitempty"`

	// The name of the residence, if any
	Residence string `json:"residence,omitempty"`

	// The identifier of the stair, if any
	Stair string `json:"stair,omitempty"`

	Street XdslEligibilityStreet `json:"street,omitempty"`

	// The number in the street
	StreetNumber string `json:"streetNumber,omitempty"`
}
