/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Customer action to do
type XdslLineDiagnosticCustomerActionToDo struct {

	// action's description
	Description string `json:"description,omitempty"`

	// action's name
	Name string `json:"name,omitempty"`
}
