/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// XdslLineDiagnosticLineDetails Line informations
type XdslLineDiagnosticLineDetails struct {

	// AccessName access name
	AccessName string `json:"accessName,omitempty"`

	// Address address of the access
	Address string `json:"address,omitempty"`

	// ContactPhone customer phone number for contact
	ContactPhone string `json:"contactPhone,omitempty"`

	// Description custom access description
	Description string `json:"description,omitempty"`

	// DslamIsSynchronized DSLAM is synchronized or not
	DslamIsSynchronized bool `json:"dslamIsSynchronized,omitempty"`

	// Gtr is GTR access or not
	Gtr bool `json:"gtr,omitempty"`

	// Length Line length in meters
	Length int64 `json:"length,omitempty"`

	// LineType dsl connexion type for the line
	LineType string `json:"lineType,omitempty"`

	// Nra NRA name
	Nra string `json:"nra,omitempty"`

	// Number line number
	Number string `json:"number,omitempty"`

	// Operator provider for internet connexion
	Operator string `json:"operator,omitempty"`

	// Sections cables sections details
	Sections []*XdslLineDiagnosticSection `json:"sections,omitempty"`
}
