/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Diagnostic status and informations
type XdslLineDiagnosticDiagnostic struct {

	Data XdslLineDiagnosticDiagnosticData `json:"data,omitempty"`

	// Diagnostic id
	Id int64 `json:"id,omitempty"`

	// Diagnostic status
	Status string `json:"status,omitempty"`
}
