/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// XdslLineDiagnosticQuestion Question to customer
type XdslLineDiagnosticQuestion struct {

	// DefaultValue question description
	DefaultValue string `json:"defaultValue,omitempty"`

	// Description question description
	Description string `json:"description,omitempty"`

	// Name question name
	Name string `json:"name,omitempty"`

	// PossibleValues list of possible values
	PossibleValues []*XdslLineDiagnosticPossibleValue `json:"possibleValues,omitempty"`

	// Required is a required question
	Required bool `json:"required,omitempty"`

	// TType answer type
	TType string `json:"type,omitempty"`
}
