/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// Information about the reason for the resiliation
type XdslResiliationSurvey struct {

	// Comment about this resiliation
	Comment string `json:"comment,omitempty"`

	// Type of reason for the resiliation
	Type_ string `json:"type,omitempty"`
}
