/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

import (
	"time"
)

// XdslIncident Detected incident
type XdslIncident struct {
	Comment string `json:"comment,omitempty"`

	// CreationDate Estimated start date
	CreationDate *time.Time `json:"creationDate,omitempty"`

	// Departments Department list
	Departments []string `json:"departments,omitempty"`

	// EndDate Estimated end date
	EndDate *time.Time `json:"endDate,omitempty"`

	// ID ID of the incident
	ID int64 `json:"id,omitempty"`

	// Nra NRA list
	Nra []string `json:"nra,omitempty"`

	// Operators Operator
	Operators []string `json:"operators,omitempty"`

	// TaskID Task ID on travaux.ovh.com
	TaskID int64 `json:"taskId,omitempty"`
}
