/* 
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// DHCP Static Address
type XdslDhcpStaticAddress struct {

	// The IP address of the device
	IPAddress string `json:"IPAddress,omitempty"`

	// The MAC address of the device
	MACAddress string `json:"MACAddress,omitempty"`

	// Name of the DHCP Static lease
	Name string `json:"name,omitempty"`

	// ID of the ongoing todo (NULL if none)
	TaskId int64 `json:"taskId,omitempty"`
}
