/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// XdslLinesDiagnosticRunPost ...
type XdslLinesDiagnosticRunPost struct {
	ActionsDone []string `json:"actionsDone,omitempty"`

	Answers *XdslLineDiagnosticAnswers `json:"answers,omitempty"`

	FaultType string `json:"faultType,omitempty"`
}
