/*
 * OVH API - EU
 *
 * Build your own OVH world.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-subscribe@ml.ovh.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package types

// ZoneStatus Zone status
type ZoneStatus struct {

	// Errors Error list
	Errors []string `json:"errors,omitempty"`

	// IsDeployed True if the zone has successfully been deployed
	IsDeployed bool `json:"isDeployed,omitempty"`

	// Warnings Warning list
	Warnings []string `json:"warnings,omitempty"`
}
